# Generated by Django 5.2.12 on 2026-03-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
