# Generated by Django 5.2.12 on 2026-03-06 15:39

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя артиста')),
                ('slug', models.SlugField(max_length=254, unique=True, verbose_name='slug')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('city', models.CharField(blank=True, max_length=254, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Город')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(3000)], verbose_name='Об исполнителе')),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_artists', to=settings.AUTH_USER_MODEL, verbose_name='Менеджеры')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Профиль артиста')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'артисты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtistLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('link_type', models.CharField(choices=[('contact', 'Контакт'), ('social', 'Соцсеть')], max_length=32, verbose_name='Тип ссылки')),
                ('label', models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название')),
                ('value', models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Значение')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='users.artistprofile', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'Ссылка артиста',
                'verbose_name_plural': 'ссылки артиста',
                'ordering': ['-created_at', 'link_type', 'label', 'value'],
            },
        ),
    ]
