# Generated by Django 5.2.12 on 2026-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_coreuser_email_artistprofile_artistlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, unique=True, verbose_name='slug'),
        ),
    ]
