# Generated by Django 5.2.12 on 2026-03-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_artistprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='cover',
            field=models.ImageField(blank=True, upload_to='artists/covers', verbose_name='Обложка'),
        ),
    ]
