# Generated by Django 5.2.12 on 2026-03-06 19:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_artistprofile_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('label', models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название контакта')),
                ('value', models.EmailField(max_length=254, verbose_name='Контакт')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='users.artistprofile', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'Контакт артиста',
                'verbose_name_plural': 'контакты артиста',
                'ordering': ['-created_at', 'label', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ArtistSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('label', models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название соцсети')),
                ('value', models.URLField(verbose_name='Ссылка')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='users.artistprofile', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'Соцсеть артиста',
                'verbose_name_plural': 'соцсети артиста',
                'ordering': ['-created_at', 'label', 'value'],
            },
        ),
        migrations.DeleteModel(
            name='ArtistLink',
        ),
    ]
