# Generated by Django 5.2.12 on 2026-03-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_artistcontact_artistsocial_delete_artistlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='managers',
        ),
    ]
