# Generated by Django 5.2.12 on 2026-03-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_coreuser_email'),
        ('users', '0006_remove_artistprofile_managers'),
    ]

    operations = [
    ]
