# Generated by Django 5.2.12 on 2026-03-09 15:50

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_artistprofile_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона', max_length=50, region=None, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listener_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Слушатель',
                'verbose_name_plural': 'слушатели',
            },
        ),
    ]
