# Generated by Django 5.2.12 on 2026-03-14 09:26

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_listenerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistcontact',
            options={'ordering': ('-created_at', 'label', 'value'), 'verbose_name': 'контакт артиста', 'verbose_name_plural': 'контакты артиста'},
        ),
        migrations.AlterModelOptions(
            name='artistprofile',
            options={'ordering': ('name',), 'verbose_name': 'артист', 'verbose_name_plural': 'артисты'},
        ),
        migrations.AlterModelOptions(
            name='artistsocial',
            options={'ordering': ('-created_at', 'label', 'value'), 'verbose_name': 'соцсеть артиста', 'verbose_name_plural': 'соцсети артиста'},
        ),
        migrations.AlterModelOptions(
            name='coreuser',
            options={'ordering': ('-date_joined', 'username'), 'verbose_name': 'учетная запись', 'verbose_name_plural': 'учетные записи'},
        ),
        migrations.AlterModelOptions(
            name='listenerprofile',
            options={'verbose_name': 'слушатель', 'verbose_name_plural': 'слушатели'},
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='artists/covers', validators=[store.validators.validate_file_size], verbose_name='Обложка артиста'),
        ),
    ]
