# Generated by Django 5.2.12 on 2026-03-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_listenerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistcontact',
            options={'ordering': ['-created_at', 'label', 'value'], 'verbose_name': 'контакт артиста', 'verbose_name_plural': 'контакты артиста'},
        ),
        migrations.AlterModelOptions(
            name='artistprofile',
            options={'ordering': ['name'], 'verbose_name': 'артист', 'verbose_name_plural': 'артисты'},
        ),
        migrations.AlterModelOptions(
            name='artistsocial',
            options={'ordering': ['-created_at', 'label', 'value'], 'verbose_name': 'соцсеть артиста', 'verbose_name_plural': 'соцсети артиста'},
        ),
        migrations.AlterModelOptions(
            name='coreuser',
            options={'ordering': ['-date_joined', 'username'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterModelOptions(
            name='listenerprofile',
            options={'verbose_name': 'слушатель', 'verbose_name_plural': 'слушатели'},
        ),
    ]
