# Generated by Django 5.2.12 on 2026-03-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_artistcontact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден'),
        ),
    ]
