# Generated by Django 5.2.12 on 2026-03-20 16:29

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_artistcontact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listenerprofile',
            options={'ordering': ('-created_at',), 'verbose_name': 'слушатель', 'verbose_name_plural': 'слушатели'},
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Имя и фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='listenerprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона', max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
