# Generated by Django 5.2.12 on 2026-03-24 14:21

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_artist_owner_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listenerprofile',
            options={'ordering': ('-created_at', 'full_name'), 'verbose_name': 'слушатель', 'verbose_name_plural': 'слушатели'},
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='listenerprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='coreuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Телефон подтвержден'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер телефона', max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Имя и фамилия'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись'),
        ),
        migrations.AlterField(
            model_name='listenerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listener_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись'),
        ),
    ]
