# Generated by Django 5.2.12 on 2026-04-23 15:11

import django.db.models.deletion
import users.validators.legal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_listenerprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistLegalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('recipient_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('self_employed', 'Самозанятый'), ('individual_entrepreneur', 'ИП'), ('legal_entity', 'Юридическое лицо')], max_length=32, verbose_name='Тип получателя')),
                ('recipient_name', models.CharField(blank=True, max_length=150, verbose_name='Наименование получателя')),
                ('taxation_system', models.CharField(blank=True, choices=[('', 'Не указано'), ('npd', 'НПД (самозанятый)'), ('usn', 'УСН'), ('osno', 'ОСНО'), ('patent', 'Патент')], default='', max_length=16, verbose_name='Система налогообложения')),
                ('is_verified', models.BooleanField(default=False, help_text='Данные проверены вручную.', verbose_name='Проверено')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись')),
            ],
            options={
                'verbose_name': 'юридический профиль артиста',
                'verbose_name_plural': 'юридические профили артистов',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ArtistIdentityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, validators=[users.validators.legal.validate_birth_date], verbose_name='Дата рождения')),
                ('registration_address', models.CharField(blank=True, max_length=500, verbose_name='Адрес регистрации')),
                ('passport_series', models.CharField(blank=True, max_length=4, validators=[users.validators.legal.validate_passport_series], verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=6, validators=[users.validators.legal.validate_passport_number], verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан паспорт')),
                ('passport_issue_date', models.DateField(blank=True, null=True, validators=[users.validators.legal.validate_passport_issue_date], verbose_name='Дата выдачи паспорта')),
                ('legal_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_data', to='users.artistlegalprofile', verbose_name='Юридический профиль')),
            ],
            options={
                'verbose_name': 'паспортные данные',
                'verbose_name_plural': 'паспортные данные',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ArtistBankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('inn', models.CharField(blank=True, max_length=12, validators=[users.validators.legal.validate_inn], verbose_name='ИНН')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Название банка')),
                ('bik', models.CharField(blank=True, max_length=9, validators=[users.validators.legal.validate_bik], verbose_name='БИК')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, validators=[users.validators.legal.validate_correspondent_account], verbose_name='Корреспондентский счет')),
                ('checking_account', models.CharField(blank=True, max_length=20, validators=[users.validators.legal.validate_checking_account], verbose_name='Расчетный счет')),
                ('legal_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_data', to='users.artistlegalprofile', verbose_name='Юридический профиль')),
            ],
            options={
                'verbose_name': 'банковские данные',
                'verbose_name_plural': 'банковские данные',
                'ordering': ('-updated_at',),
            },
        ),
    ]
