# Generated by Django 5.2.12 on 2026-04-25 17:35

import encrypted_fields.fields
import users.validators.legal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_artistlegalprofile_artistidentitydata_artistbankdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistbankdata',
            name='checking_account',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, validators=[users.validators.legal.validate_checking_account], verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='artistbankdata',
            name='correspondent_account',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, validators=[users.validators.legal.validate_correspondent_account], verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='artistbankdata',
            name='inn',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=12, validators=[users.validators.legal.validate_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='birth_date',
            field=encrypted_fields.fields.EncryptedDateField(blank=True, null=True, validators=[users.validators.legal.validate_birth_date], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='first_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='last_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='middle_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='passport_issue_date',
            field=encrypted_fields.fields.EncryptedDateField(blank=True, null=True, validators=[users.validators.legal.validate_passport_issue_date], verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='passport_issued_by',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='passport_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=6, validators=[users.validators.legal.validate_passport_number], verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='passport_series',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=4, validators=[users.validators.legal.validate_passport_series], verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='registration_address',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='artistlegalprofile',
            name='recipient_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=150, verbose_name='Наименование получателя'),
        ),
    ]
