# Generated by Django 5.2.12 on 2026-04-29 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_artistlegalprofile_artistidentitydata_artistbankdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название документа')),
                ('slug', models.SlugField(help_text='Разрешены только буквы, цифры, дефисы и подчеркивания. Должен быть уникальным.', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'тип документа',
                'verbose_name_plural': 'типы документов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ConsentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('version', models.CharField(max_length=20, verbose_name='Версия')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='hash документа')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'юридический документ',
                'verbose_name_plural': 'юридические документы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('email', models.EmailField(max_length=254)),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время принятия согласия', verbose_name='Дата соглашения')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP-адрес пользователя в момент принятия', null=True, verbose_name='IP-address')),
                ('user_agent', models.TextField(blank=True, help_text='Agent клиента пользователя', null=True, verbose_name='Пользовательский агент')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.consentdocument', verbose_name='Принятый документ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'согласие пользователя',
                'verbose_name_plural': 'согласия пользователя',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='consentdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document_type',), name='unique_active_document_per_type', violation_error_message='Уже существует активный документ такого типа. Сначала деактивируйте старый документ.'),
        ),
        migrations.AddConstraint(
            model_name='consentdocument',
            constraint=models.UniqueConstraint(fields=('document_type', 'version'), name='unique_document_version'),
        ),
    ]
