# Generated by Django 5.2.12 on 2026-05-06 14:59

import users.validators.legal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_documenttype_consentdocument_userconsent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistbankdata',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='artistlegalprofile',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='artistlegalprofile',
            name='taxation_system',
        ),
        migrations.AddField(
            model_name='artistidentitydata',
            name='inn',
            field=models.CharField(blank=True, max_length=12, validators=[users.validators.legal.validate_person_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='artistlegalprofile',
            name='recipient_type',
            field=models.CharField(choices=[('individual_entrepreneur', 'ИП'), ('self_employed', 'СМЗ'), ('legal_entity', 'Юридическое лицо')], max_length=32, verbose_name='Организационная форма'),
        ),
    ]
