# Generated by Django 5.2.12 on 2026-05-06 15:09

import django.db.models.deletion
import users.validators.legal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_documenttype_consentdocument_userconsent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistbankdata',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='artistlegalprofile',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='artistlegalprofile',
            name='taxation_system',
        ),
        migrations.AddField(
            model_name='artistidentitydata',
            name='inn',
            field=models.CharField(blank=True, max_length=12, validators=[users.validators.legal.validate_person_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='artistlegalprofile',
            name='recipient_type',
            field=models.CharField(choices=[('individual_entrepreneur', 'ИП'), ('self_employed', 'СМЗ'), ('legal_entity', 'Юридическое лицо')], max_length=32, verbose_name='Организационная форма'),
        ),
        migrations.CreateModel(
            name='ArtistCompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Наименование получателя')),
                ('company_address', models.CharField(blank=True, max_length=500, verbose_name='Юридический адрес')),
                ('inn', models.CharField(blank=True, max_length=10, validators=[users.validators.legal.validate_company_inn], verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=13, validators=[users.validators.legal.validate_ogrn], verbose_name='ОГРН')),
                ('legal_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_data', to='users.artistlegalprofile', verbose_name='Юридический профиль')),
            ],
            options={
                'verbose_name': 'данные юридического лица',
                'verbose_name_plural': 'данные юридических лиц',
                'ordering': ('-updated_at',),
            },
        ),
    ]
