# Generated by Django 5.2.12 on 2026-05-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_artistbankdata_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentdocument',
            name='document_type',
            field=models.CharField(choices=[('privacy_policy', 'Политика обработки персональных данных'), ('artist_offer', 'Артист: Договор-оферта'), ('artist_personal_data', 'Артист: Согласие на обработку ПДн'), ('artist_distribution', 'Артист: Согласие на распространение ПДн'), ('artist_newsletter', 'Артист: Согласие на получение рассылки'), ('listener_offer', 'Слушатель: Договор-оферта'), ('listener_personal_data', 'Слушатель: Согласие на обработку ПДн'), ('listener_distribution', 'Слушатель: Согласие на распространение ПДн'), ('listener_newsletter', 'Слушатель: Согласие на рассылку')], max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AlterModelOptions(
            name='consentdocument',
            options={'ordering': ('document_type', '-created_at'), 'verbose_name': 'юридический документ', 'verbose_name_plural': 'юридические документы'},
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
