# Generated by Django 5.2.12 on 2026-05-07 13:53

import encrypted_fields.fields
import users.validators.legal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_artistbankdata_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistbankdata',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='artistbankdata',
            name='bik',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[users.validators.legal.validate_bik], verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='artistbankdata',
            name='checking_account',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[users.validators.legal.validate_checking_account], verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='artistbankdata',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[users.validators.legal.validate_correspondent_account], verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='artistcompanydata',
            name='company_address',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='artistcompanydata',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименование получателя'),
        ),
        migrations.AlterField(
            model_name='artistcompanydata',
            name='inn',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=10, null=True, validators=[users.validators.legal.validate_company_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='artistcompanydata',
            name='ogrn',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=13, null=True, validators=[users.validators.legal.validate_ogrn], verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='birth_date',
            field=encrypted_fields.fields.EncryptedDateField(blank=True, null=True, validators=[users.validators.legal.validate_birth_date], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='first_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='last_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='middle_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='passport_issue_date',
            field=encrypted_fields.fields.EncryptedDateField(blank=True, null=True, validators=[users.validators.legal.validate_passport_issue_date], verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='passport_issued_by',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='passport_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=6, null=True, validators=[users.validators.legal.validate_passport_number], verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='passport_series',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=4, null=True, validators=[users.validators.legal.validate_passport_series], verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='artistidentitydata',
            name='registration_address',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='artistlegalprofile',
            name='recipient_type',
            field=models.CharField(blank=True, choices=[('', 'Не указано'), ('individual_entrepreneur', 'ИП'), ('self_employed', 'СМЗ'), ('legal_entity', 'Юридическое лицо')], default='', max_length=32, verbose_name='Организационная форма'),
        ),
    ]
