# Generated by Django 5.2.12 on 2026-05-08 11:46

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_consentdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistlegalprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email для юридических документов'),
        ),
        migrations.AddField(
            model_name='artistlegalprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон для юридических документов'),
        ),
        migrations.AlterField(
            model_name='artistlegalprofile',
            name='recipient_type',
            field=models.CharField(blank=True, choices=[('', 'Не указано'), ('individual_entrepreneur', 'ИП'), ('self_employed', 'СМЗ'), ('legal_entity', 'Юридическое лицо')], default='', max_length=32, verbose_name='Организационная форма'),
        ),
    ]
