# Generated by Django 5.2.12 on 2026-05-11 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_artistlegalprofile_email_artistlegalprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='users.artistprofile', verbose_name='Объект подписки'),
        ),
        migrations.AlterField(
            model_name='consentdocument',
            name='document_type',
            field=models.CharField(choices=[('privacy_policy', 'Политика обработки персональных данных'), ('artist_offer', 'Артист: Договор-оферта'), ('artist_personal_data', 'Артист: Согласие на обработку ПДн'), ('artist_distribution', 'Артист: Согласие на распространение ПДн'), ('artist_newsletter', 'Артист: Согласие на получение рассылки'), ('listener_offer', 'Слушатель: Договор-оферта'), ('listener_personal_data', 'Слушатель: Согласие на обработку ПДн'), ('listener_distribution', 'Слушатель: Согласие на распространение ПДн'), ('listener_newsletter', 'Слушатель: Согласие на получение рассылки')], max_length=50, verbose_name='Тип документа'),
        ),
    ]
