# Generated by Django 5.2.12 on 2026-06-13 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userconsent_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistPickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='users.artistprofile', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'пункт самовывоза артиста',
                'verbose_name_plural': 'пункты самовывоза артистов',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ArtistShippingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('pvz_code', models.CharField(max_length=32, verbose_name='Код ПВЗ СДЭК для отправки')),
                ('city_code', models.CharField(max_length=32, verbose_name='Код населенного пункта СДЭК')),
                ('city', models.CharField(max_length=254, verbose_name='Название населенного пункта')),
                ('address', models.CharField(max_length=500, verbose_name='Строка адреса')),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_point', to='users.artistprofile', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'точка отправки заказов',
                'verbose_name_plural': 'точка отправки заказов',
            },
        ),
    ]
