# Generated by Django 5.2.12 on 2026-06-16 10:44

import common.storages
import store.validators
import users.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_artistpickuppoint_artistshippingpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=common.storages.get_public_media_storage, upload_to=users.upload_paths.artist_cover_upload_to, validators=[store.validators.validate_file_size], verbose_name='Обложка артиста'),
        ),
    ]
