# Generated by Django 5.2.12 on 2026-06-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_artistprofile_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='telegram_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
