# Generated by Django 5.2.12 on 2026-07-16 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from store.migrations.utils import drop_view, create_view


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_artistprofile_telegram_chat_id_and_more'),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AddField(
            model_name='artistprofile',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artists', to='users.artistprofile', verbose_name='Лейбл'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='profile_type',
            field=models.CharField(choices=[('artist', 'Артист'), ('label', 'Лейбл')], default='artist', max_length=32, verbose_name='Тип профиля'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись'),
        ),
        migrations.AddConstraint(
            model_name='artistprofile',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('label__isnull', False), _connector='OR'), name='artist_profile_has_user_or_label'),
        ),
        migrations.AddConstraint(
            model_name='artistprofile',
            constraint=models.CheckConstraint(condition=models.Q(('profile_type', 'artist'), ('user__isnull', False), _connector='OR'), name='label_profile_has_user'),
        ),
        migrations.AddConstraint(
            model_name='artistprofile',
            constraint=models.CheckConstraint(condition=models.Q(('profile_type', 'artist'), ('label__isnull', True), _connector='OR'), name='label_profile_has_no_parent_label'),
        ),
        migrations.AddConstraint(
            model_name='artistprofile',
            constraint=models.CheckConstraint(condition=models.Q(('label__isnull', True), models.Q(('pk', models.F('label')), _negated=True), _connector='OR'), name='profile_is_not_its_own_label'),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
