# Generated by Django 5.2.12 on 2026-07-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_artistprofile_label_artistprofile_profile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='label',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile_type': 'label'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artists', to='users.artistprofile', verbose_name='Лейбл'),
        ),
    ]
