# Generated by Django 5.2.12 on 2026-07-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_artistprofile_label'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artistpickuppoint',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('artist', 'address', 'pickup_date'), name='unique_active_artist_pickup_point', nulls_distinct=False),
        ),
    ]
