# Generated by Django 5.2.12 on 2026-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_artistprofile_label'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artistpickuppoint',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('address', 'pickup_date'), name='unique_active_address_pickup_date'),
        ),
    ]
