# Generated by Django 5.2.12 on 2026-08-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_artistpickuppoint_unique_active_artist_pickup_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='url',
        ),
    ]
