# Generated by Django 5.2.12 on 2026-08-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_artistprofile_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistStoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='Email поддержки')),
                ('returns_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для возвратов')),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to='users.artistprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'настройки магазина',
                'verbose_name_plural': 'настройки магазинов',
            },
        ),
    ]
