# Generated by Django 5.2.12 on 2026-08-11 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_artiststoresettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('token_hash', models.CharField(max_length=128, unique=True, verbose_name='Хеш токена')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('revoked', 'Отозвано'), ('expired', 'Истекло')], default='pending', max_length=16, verbose_name='Статус')),
                ('send_count', models.PositiveIntegerField(default=0, verbose_name='Количество отправок')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней отправки')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_token_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responded_token_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Ответивший пользователь')),
            ],
            options={
                'verbose_name': 'инвайт',
                'verbose_name_plural': 'инвайты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ArtistProfileClaimInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_invitations', to='users.artistprofile', verbose_name='Профиль артиста')),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile_claim', to='users.tokeninvitation', verbose_name='Приглашение')),
            ],
            options={
                'verbose_name': 'приглашение на управление профилем',
                'verbose_name_plural': 'приглашения на управление профилем',
            },
        ),
    ]
