# Generated by Django 5.2.12 on 2026-08-17 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_tokeninvitation_artistprofileclaiminvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Хэш кода')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Количество попыток')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_code', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'код подтверждения email',
                'verbose_name_plural': 'коды подтверждения email',
            },
        ),
    ]
