# Generated by Django 5.2.12 on 2026-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='revocation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отзыва'),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отзыва'),
        ),
    ]
