# Generated by Django 5.2.12 on 2026-09-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_userconsent_revoked_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistpickuppoint',
            options={'ordering': ('id',), 'verbose_name': 'точка самовывоза артиста', 'verbose_name_plural': 'точки самовывоза артистов'},
        ),
    ]
