# Generated by Django 5.2.12 on 2026-09-08 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_artistpickuppoint_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistcontact',
            name='label',
            field=models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название контакта'),
        ),
        migrations.AlterField(
            model_name='artistsocial',
            name='label',
            field=models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название соцсети'),
        ),
    ]
