# Generated by Django 5.2.12 on 2026-09-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_artistcontact_label_alter_artistsocial_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiststoresettings',
            name='pickup_enabled',
            field=models.BooleanField(default=False, verbose_name='Самовывоз включён'),
        ),
        migrations.AddField(
            model_name='artiststoresettings',
            name='shipping_enabled',
            field=models.BooleanField(default=False, verbose_name='Доставка СДЭК включена'),
        ),
    ]
