# Generated by Django 5.2.12 on 2026-09-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_artiststoresettings_pickup_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiststoresettings',
            name='returns_email',
        ),
        migrations.RemoveField(
            model_name='artiststoresettings',
            name='support_email',
        ),
    ]
