# Generated by Django 5.2.12 on 2026-09-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_encrypt_legal_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artistprofile',
            name='artist_profile_has_user_or_label',
        ),
        migrations.RemoveConstraint(
            model_name='artistprofile',
            name='label_profile_has_user',
        ),
    ]
