# Generated by Django 5.2.12 on 2026-03-06 16:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('genre', models.CharField(max_length=256, verbose_name='Жанр')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Цена, руб.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('allow_fans_to_pay_more', models.BooleanField(default=False, help_text='Если включено, фанаты смогут заплатить больше стоимости.', verbose_name='Разрешить платить больше')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('genre', models.CharField(max_length=256, verbose_name='Жанр')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Цена, руб.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('allow_fans_to_pay_more', models.BooleanField(default=False, help_text='Если включено, фанаты смогут заплатить больше стоимости.', verbose_name='Разрешить платить больше')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'сингл',
                'verbose_name_plural': 'Синглы',
            },
        ),
    ]
