# Generated by Django 5.2.12 on 2026-03-09 02:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Цена, руб.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('allow_fans_to_pay_more', models.BooleanField(default=False, help_text='Если включено, фанаты смогут заплатить больше стоимости.', verbose_name='Разрешить платить больше')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers', verbose_name='Обложка релиза')),
                ('visibility', models.CharField(choices=[('public', 'Опубликовано'), ('link_only', 'Доступно по ссылке'), ('hidden', 'Скрыто')], default='public', max_length=20, verbose_name='Приватность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='store.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-release_date'],
            },
        ),
    ]
