# Generated by Django 5.2.12 on 2026-03-07 09:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single',
            name='user',
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('release_type', models.CharField(choices=[('single', 'Сингл'), ('album', 'Альбом')], max_length=10, verbose_name='Тип релиза')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('genre', models.CharField(max_length=256, verbose_name='Жанр')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Цена, руб.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('allow_fans_to_pay_more', models.BooleanField(default=False, help_text='Если включено, фанаты смогут заплатить больше стоимости.', verbose_name='Разрешить платить больше')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='release_covers', verbose_name='Обложка релиза')),
                ('visibility', models.CharField(choices=[('public', 'Опубликовано'), ('link_only', 'Доступно по ссылке'), ('hidden', 'Скрыто')], default='public', max_length=20, verbose_name='Приватность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'релиз',
                'verbose_name_plural': 'Релизы',
            },
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Single',
        ),
    ]
