# Generated by Django 5.2.12 on 2026-03-09 02:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-release_date',), 'verbose_name': 'альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('audio_file', models.FileField(help_text='Аудиофайл', upload_to='tracks/', verbose_name='Файл трека')),
                ('individual_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Цена, руб.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена трека')),
                ('allow_fans_to_pay_more', models.BooleanField(default=False, help_text='Если включено, фанаты смогут заплатить больше стоимости.', verbose_name='Разрешить платить больше')),
                ('lyrics', models.TextField(blank=True, default='', verbose_name='Текст трека')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='store.album', verbose_name='Альбом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'трек',
                'verbose_name_plural': 'Треки',
                'ordering': ('album', 'name'),
            },
        ),
    ]
