# Generated by Django 5.2.12 on 2026-03-09 13:15

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_album_options_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=1, help_text='Разрешены только буквы, цифры, дефисы и подчеркивания. Должен быть уникальным.', unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers', validators=[store.validators.validate_file_size], verbose_name='Обложка релиза'),
        ),
    ]
