# Generated by Django 5.2.12 on 2026-03-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_kind_albummerch_merch_image_and_more'),
        ('store', '0003_genre_slug_alter_album_cover_image'),
    ]

    operations = [
    ]
