# Generated by Django 5.2.12 on 2026-03-12 20:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_genre_slug_alter_album_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'тип мерча',
                'verbose_name_plural': 'типы мерча',
            },
        ),
        migrations.CreateModel(
            name='AlbumMerch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'альбом и мерч',
                'verbose_name_plural': 'альбомы и мерчи',
                'ordering': ['-created_at'],
                'default_related_name': 'album_merch',
            },
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('allow_fans_overpay', models.BooleanField(default=False, verbose_name='Разрешение платить больше')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('visibility', models.CharField(choices=[('public', 'Опубликовано'), ('link_only', 'Доступно по ссылке'), ('hidden', 'Скрыто')], default='public', max_length=20, verbose_name='Приватность')),
                ('characteristic', models.JSONField(blank=True, default=dict, verbose_name='Свойства')),
                ('album', models.ManyToManyField(blank=True, related_name='merch', through='store.AlbumMerch', to='store.album', verbose_name='Альбом')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merch', to='store.category', verbose_name='Категория')),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merch', to='store.kind', verbose_name='Тип')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'мерч',
                'verbose_name_plural': 'мерчи',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='photos_merch/', verbose_name='Фото')),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_merch', to='store.merch', verbose_name='Мерч')),
            ],
            options={
                'verbose_name': 'фото мерча',
                'verbose_name_plural': 'фотографии мерча',
            },
        ),
        migrations.AddField(
            model_name='albummerch',
            name='merch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.merch', verbose_name='Мерч'),
        ),
        migrations.AddConstraint(
            model_name='albummerch',
            constraint=models.UniqueConstraint(fields=('album', 'merch'), name='unique_album_merch'),
        ),
    ]
