# Generated by Django 5.2.12 on 2026-03-09 12:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_property_type_merch_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='image',
            name='max_images_for_merch',
        ),
        migrations.AlterField(
            model_name='merch',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена'),
        ),
    ]
