# Generated by Django 5.2.12 on 2026-03-12 11:56

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_kind_albummerch_merch_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-release_date',), 'verbose_name': 'альбом', 'verbose_name_plural': 'альбомы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('album', 'track_number', 'name'), 'verbose_name': 'трек', 'verbose_name_plural': 'треки'},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='allow_fans_to_pay_more',
            new_name='allow_fans_overpay',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='allow_fans_to_pay_more',
            new_name='allow_fans_overpay',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='album',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='album',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Если включено, объект виден пользователям.', verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='album',
            name='is_single',
            field=models.BooleanField(default=False, verbose_name='Сингл'),
        ),
        migrations.AddField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Длительность трека в секундах', null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='track',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='track',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, help_text='Порядок трека в альбоме', null=True, verbose_name='Номер трека'),
        ),
        migrations.AddField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='album',
            name='visibility',
            field=models.CharField(choices=[('public', 'Для всех'), ('link_only', 'Доступно по ссылке'), ('hidden', 'Скрыто')], default='public', max_length=20, verbose_name='Приватность'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(help_text='Аудиофайл', upload_to='tracks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp3', 'wav', 'flac'))], verbose_name='Файл трека'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('album', 'track_number'), name='unique_track_number_per_album'),
        ),
    ]
