# Generated by Django 5.2.12 on 2026-03-14 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_kind_albummerch_merch_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.album', verbose_name='Альбом')),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Слушатель')),
                ('merch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.merch', verbose_name='Мерч')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.track', verbose_name='Трек')),
            ],
            options={
                'verbose_name': 'избранные',
                'verbose_name_plural': 'избранное',
                'ordering': ['-created_at'],
                'default_related_name': 'favorited_by',
            },
        ),
    ]
