# Generated by Django 5.2.12 on 2026-03-20 09:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_album_options_alter_genre_options_and_more'),
        ('users', '0008_alter_artistcontact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('track', 'Track'), ('album', 'Album'), ('merch', 'Merch')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Цена, руб.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('allow_fans_overpay', models.BooleanField(default=False, help_text='Если включено, фанаты смогут заплатить больше стоимости.', verbose_name='Разрешить платить больше')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.RemoveConstraint(
            model_name='track',
            name='unique_track_number_per_album',
        ),
        migrations.RemoveField(
            model_name='album',
            name='allow_fans_overpay',
        ),
        migrations.RemoveField(
            model_name='album',
            name='price',
        ),
        migrations.RemoveField(
            model_name='track',
            name='allow_fans_overpay',
        ),
        migrations.RemoveField(
            model_name='track',
            name='individual_price',
        ),
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.artistprofile', verbose_name='Артист'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата релиза'),
        ),
        migrations.AlterField(
            model_name='track',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.artistprofile', verbose_name='Артист'),
        ),
        migrations.AddField(
            model_name='product',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.album'),
        ),
        migrations.AddField(
            model_name='product',
            name='merch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.merch'),
        ),
        migrations.AddField(
            model_name='product',
            name='track',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.track'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('album__isnull', False), ('merch__isnull', True), ('track__isnull', True), ('type', 'album')), models.Q(('album__isnull', True), ('merch__isnull', True), ('track__isnull', False), ('type', 'track')), models.Q(('album__isnull', True), ('merch__isnull', False), ('track__isnull', True), ('type', 'merch')), _connector='OR'), name='store_product_target_integrity'),
        ),
    ]
