# Generated by Django 5.2.12 on 2026-03-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_album_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kind',
            new_name='MerchKind',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='category',
        ),
        migrations.AddField(
            model_name='merch',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Если включено, объект виден пользователям.', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='visibility',
            field=models.CharField(choices=[('public', 'Для всех'), ('link_only', 'Доступно по ссылке'), ('hidden', 'Скрыто')], default='public', max_length=20, verbose_name='Приватность'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
