# Generated by Django 5.2.12 on 2026-03-24 13:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_album_options_alter_genre_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('track', 'Track'), ('album', 'Album'), ('merch', 'Merch')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Цена, руб.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('allow_overpay', models.BooleanField(default=False, help_text='Если включено, фанаты смогут заплатить больше стоимости.', verbose_name='Разрешить платить больше')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=256, unique=True, verbose_name='SKU')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Наличие на складе', verbose_name='Доступно')),
                ('characteristic', models.JSONField(blank=True, default=dict, verbose_name='Свойства')),
            ],
            options={
                'verbose_name': 'вариант продукта',
                'verbose_name_plural': 'варианты продукта',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-created_at',), 'verbose_name': 'альбом', 'verbose_name_plural': 'альбомы'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('album', 'position', 'name'), 'verbose_name': 'трек', 'verbose_name_plural': 'треки'},
        ),
        migrations.RemoveConstraint(
            model_name='track',
            name='unique_track_number_per_album',
        ),
        migrations.RemoveField(
            model_name='album',
            name='allow_fans_overpay',
        ),
        migrations.RemoveField(
            model_name='album',
            name='price',
        ),
        migrations.RemoveField(
            model_name='track',
            name='allow_fans_overpay',
        ),
        migrations.RemoveField(
            model_name='track',
            name='individual_price',
        ),
        migrations.RemoveField(
            model_name='track',
            name='track_number',
        ),
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='track',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='Порядковый номер трека в альбоме', null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Артист'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата релиза'),
        ),
        migrations.AlterField(
            model_name='track',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Артист'),
        ),
        migrations.AddField(
            model_name='product',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.album'),
        ),
        migrations.AddField(
            model_name='product',
            name='merch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.merch'),
        ),
        migrations.AddField(
            model_name='product',
            name='track',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.track'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product', verbose_name='Вариант продукта'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('product_type', 'album'), ('album__isnull', False), ('track__isnull', True), ('merch__isnull', True)), models.Q(('product_type', 'track'), ('track__isnull', False), ('album__isnull', True), ('merch__isnull', True)), models.Q(('product_type', 'merch'), ('merch__isnull', False), ('album__isnull', True), ('track__isnull', True)), _connector='OR')), name='store_product_integrity'),
        ),
    ]
