# Generated by Django 5.2.12 on 2026-03-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_album_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kind',
            new_name='MerchKind',
        ),
    ]
