# Generated by Django 5.2.12 on 2026-03-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_productvariant_alter_album_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Наличие на складе', null=True, verbose_name='Доступно'),
        ),
    ]
