# Generated by Django 5.2.12 on 2026-03-26 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_productvariant_alter_album_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kind',
            new_name='MerchKind',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='category',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='allow_fans_overpay',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='characteristic',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='price',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='quantity',
        ),
        migrations.AddField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='merch',
            name='is_carrier',
            field=models.BooleanField(default=False, verbose_name='Носитель'),
        ),
        migrations.AddField(
            model_name='merch',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Если включено, объект виден пользователям.', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Артист'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='visibility',
            field=models.CharField(choices=[('public', 'Для всех'), ('link_only', 'Доступно по ссылке'), ('hidden', 'Скрыто')], default='public', max_length=20, verbose_name='Приватность'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('merch',), name='unique_main_image_per_merch'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
