# Generated by Django 5.2.12 on 2026-04-01 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cartitem_shoppingcart_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Хочет заплатить, руб.', max_digits=10, null=True, verbose_name='Цена с донатом'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.productvariant', verbose_name='Продукт'),
        ),
    ]
