# Generated by Django 5.2.12 on 2026-04-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-created_at',), 'verbose_name': 'избранное', 'verbose_name_plural': 'избранное'},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='is_active',
        ),
    ]
