# Generated by Django 5.2.12 on 2026-04-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cartitem_custom_price_alter_cartitem_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Цена с донатом, руб.', max_digits=10, null=True, verbose_name='Хочет заплатить, руб.'),
        ),
    ]
