# Generated by Django 5.2.12 on 2026-04-13 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='Cart',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена с донатом, руб.', max_digits=10, null=True, verbose_name='Хочет заплатить, руб.'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('session_key__isnull', False), _connector='OR'), name='cart_has_owner'),
        ),
    ]
