# Generated by Django 5.2.12 on 2026-04-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cartitem_custom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий к артисту', max_length=300, null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
