# Generated by Django 5.2.12 on 2026-04-16 18:23

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order_number', models.CharField(editable=False, max_length=15, unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('confirmed', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='created', max_length=20, verbose_name='Статус')),
                ('full_name', models.CharField(default='', max_length=255, verbose_name='Имя и фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона', max_length=128, region=None, verbose_name='Номер телефона')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=255, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=255, verbose_name='Квартира/Офис')),
                ('items_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма товаров (руб.)')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Стоимость доставки (руб.)')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Итого (руб.)')),
                ('comment', models.TextField(blank=True, help_text='Комментарий к заказу', null=True, verbose_name='Комментарий')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.delivery', verbose_name='Способ доставки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
                'default_related_name': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Сообщение для артиста', max_length=200, null=True, verbose_name='Комментарий к заказу')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, help_text='Цена за единицу товара на момент оформления заказа', max_digits=10, verbose_name='Цена на момент покупки, руб.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Цена с донатом, руб.', max_digits=10, verbose_name='Фактическая оплата за ед., руб.')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('product_info', models.JSONField(default=dict, verbose_name='Данные о товаре (snapshot)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.productvariant', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'товар в заказе',
                'verbose_name_plural': 'товары в заказе',
                'constraints': [models.UniqueConstraint(fields=('order', 'product_variant'), name='unique_product_variant_in_order')],
            },
        ),
    ]
