# Generated by Django 5.2.12 on 2026-04-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='custom_price',
            new_name='price_with_donation',
        ),
    ]
