# Generated by Django 5.2.12 on 2026-04-03 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cartitem_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='comment',
            field=models.TextField(blank=True, help_text='Сообщение для артиста', max_length=200, null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
