# Generated by Django 5.2.12 on 2026-04-19 14:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_custom_price_cartitem_price_with_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_with_donation',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Цена с донатом, руб.', max_digits=10, null=True, verbose_name='Хочет заплатить, руб.'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10, verbose_name='Стоимость (руб.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Цена, руб.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
    ]
