# Generated by Django 5.2.12 on 2026-04-23 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_custom_price_cartitem_price_with_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='characteristic',
        ),
        migrations.AddField(
            model_name='product',
            name='property_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название свойства'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='property_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение свойства'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'property_value'), name='unique_variant_value_per_product'),
        ),
    ]
