# Generated by Django 5.2.12 on 2026-04-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_productvariant_characteristic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('track', 'Track'), ('album', 'Album'), ('merch', 'Merch')], max_length=20, verbose_name='Тип продукта'),
        ),
    ]
