# Generated by Django 5.2.12 on 2026-04-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productvariant_is_active'),
        ('store', '0014_remove_productvariant_characteristic_and_more'),
    ]

    operations = [
    ]
