# Generated by Django 5.2.12 on 2026-05-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_ordernumbercounter_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('pickpoint', 'Пункт выдачи'), ('pickup', 'Самовывоз'), ('courier', 'Курьер до двери'), ('post', 'Почта')], default='courier', max_length=20, verbose_name='Тип доставки'),
            preserve_default=False,
        ),
    ]
