# Generated by Django 5.2.12 on 2026-05-13 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_delivery_delivery_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Код может содержать только заглавные латинские буквы и цифры.', regex='^[A-Z0-9]+$')], verbose_name='Код промокода')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Размер скидки, %')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Пусто = неограничено', null=True, verbose_name='Количество использований')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Использовано раз')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_until', models.DateField(verbose_name='Действует по')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('valid_from'))), name='promocode_valid_until_gte_valid_from'), models.CheckConstraint(condition=models.Q(('discount_percent__gte', 1), ('discount_percent__lte', 100)), name='promocode_discount_percent_range')],
            },
        ),
    ]
