# Generated by Django 5.2.12 on 2026-05-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_delivery_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_artist_subscription',
            field=models.BooleanField(default=False, verbose_name='Согласие на рассылку артиста'),
        ),
    ]
