# Generated by Django 5.2.12 on 2026-05-14 17:30

import django.core.validators
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_cartitem_is_artist_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='lyrics',
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(help_text='Аудиофайл', upload_to='tracks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp3', 'wav', 'flac')), store.validators.validate_audiofile_size], verbose_name='Файл трека'),
        ),
    ]
