# Generated by Django 5.2.12 on 2026-05-14 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0020_create_listener_track_access_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerTrackAccess',
            fields=[
                (
                    'id',
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
                (
                    'track',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='store.track',
                        verbose_name='Трек',
                    ),
                ),
            ],
            options={
                'verbose_name': 'доступ к треку',
                'verbose_name_plural': 'доступы к трекам',
                'db_table': 'listener_track_access',
                'managed': False,
            },
        ),
    ]
