# Generated by Django 5.2.12 on 2026-05-20 03:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_listenertrackaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Процент'), ('FIXED', 'Фиксированная (руб)')], default='PERCENT', max_length=10, verbose_name='Тип скидки')),
                ('code', models.CharField(help_text='Код промокода может содержать только заглавные латинские буквы, цифры, дефис и подчеркивание.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_promocode_format', message='Код промокода может содержать только заглавные латинские буквы, цифры, дефис и подчеркивание.', regex='^[A-Z0-9_-]+$')], verbose_name='Код промокода')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Размер скидки')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Пусто = неограничено', null=True, verbose_name='Макс. количество использований')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Использовано раз')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало действия')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание действия')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включен')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('end_at__gt', models.F('start_at')), ('end_at__isnull', False), ('start_at__isnull', False)), ('start_at__isnull', True), ('end_at__isnull', True), _connector='OR'), name='promocode_end_at_strictly_gt_start_at'), models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'PERCENT'), ('discount_value__gt', 0), ('discount_value__lte', 100)), models.Q(('discount_type', 'FIXED'), ('discount_value__gt', 0)), _connector='OR'), name='promocode_discount_value_valid')],
            },
        ),
    ]
