# Generated by Django 5.2.12 on 2026-05-26 09:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def drop_view_and_save_sql(apps, schema_editor):
    """Динамически находит SQL создания вьюхи, сохраняет его в память и дропает вьюху."""
    if schema_editor.connection.vendor == 'sqlite':
        with schema_editor.connection.cursor() as cursor:
            # Ищем оригинальный SQL-запрос создания вьюхи в метаданных SQLite
            cursor.execute(
                "SELECT sql FROM sqlite_master WHERE type='view' AND name='listener_track_access';"
            )
            row = cursor.fetchone()
            if row and row[0]:
                # Сохраняем SQL во временный атрибут миграции, чтобы прочитать на следующем шаге
                Migration._saved_view_sql = row[0]
                # Дропаем вьюху, освобождая таблицу store_order для пересборки
                cursor.execute('DROP VIEW IF EXISTS listener_track_access;')


def restore_view(apps, schema_editor):
    """Восстанавливает вьюху обратно после того, как Django обновил таблицу."""
    if schema_editor.connection.vendor == 'sqlite' and hasattr(Migration, '_saved_view_sql'):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(Migration._saved_view_sql)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_cart_promocode'),
    ]

    operations = [
        # Перед изменением таблицы перехватываем и дропаем вьюху (только на SQLite)
        migrations.RunPython(drop_view_and_save_sql, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.promocode', verbose_name='Примененный промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode_discount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Сумма скидки по промокоду (руб.)'),
        ),

        # Возвращаем вьюху на место, используя сохраненный SQL
        migrations.RunPython(restore_view, reverse_code=migrations.RunPython.noop),
    ]
