# Generated by Django 5.2.12 on 2026-06-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_promocode_order_promocode_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='is_carrier',
        ),
        migrations.AddField(
            model_name='merchkind',
            name='is_carrier',
            field=models.BooleanField(default=False, help_text='Необходимо установить флаг, если тип является носителем.', verbose_name='Носитель'),
        ),
    ]
