# Generated by Django 5.2.12 on 2026-06-09 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from store.migrations.utils.sql_views import create_view


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0026_remove_merch_is_carrier_merchkind_is_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerAlbumAccess',
            fields=[
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
                (
                    'album',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='store.album',
                        verbose_name='Альбом',
                    ),
                ),
                (
                    'is_fully_available',
                    models.BooleanField(
                        verbose_name='Релиз доступен полностью',
                    ),
                ),
                (
                    'pk',
                    models.CompositePrimaryKey(
                        'user',
                        'album',
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                'verbose_name': 'доступ к релизу',
                'verbose_name_plural': 'доступы к релизам',
                'db_table': 'listener_album_access',
                'managed': False,
            },
        ),
        create_view('listener_album_access', version=1),
    ]
