# Generated by Django 5.2.12 on 2026-06-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_listeneralbumaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='price',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('courier', 'СДЭК - курьером до двери'), ('pickpoint', 'СДЭК - в пункт выдачи'), ('pickup', 'Самовывоз')], max_length=20, verbose_name='Тип доставки'),
        ),
    ]
