# Generated by Django 5.2.12 on 2026-06-16 10:56

import common.storages
import django.core.validators
import django.db.models.deletion
import store.upload_paths
import store.validators
from django.db import migrations, models

from store.migrations.utils import create_view, drop_view


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_delivery_description_remove_delivery_price_and_more'),
    ]

    operations = [
        drop_view('listener_track_access'),
        drop_view('listener_album_access'),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=common.storages.get_public_media_storage, upload_to=store.upload_paths.album_cover_upload_to, validators=[store.validators.validate_file_size], verbose_name='Обложка релиза'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=common.storages.get_public_media_storage, upload_to=store.upload_paths.merch_image_upload_to, validators=[store.validators.validate_file_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(help_text='Аудиофайл', storage=common.storages.get_private_media_storage, upload_to=store.upload_paths.track_audio_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp3', 'wav', 'flac')), store.validators.validate_audiofile_size], verbose_name='Файл трека'),
        ),
        migrations.CreateModel(
            name='AlbumArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(blank=True, storage=common.storages.get_private_media_storage, upload_to=store.upload_paths.album_archive_upload_to)),
                ('status', models.CharField(choices=[('pending', 'Ожидает сборки'), ('building', 'Собирается'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('content_hash', models.CharField(blank=True, help_text='SHA256 от нормализованного состава альбома, используется для проверки актуальности архива.', max_length=64, verbose_name='Отпечаток содержимого архива')),
                ('error_message', models.TextField(blank=True)),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='store.album')),
            ],
            options={
                'abstract': False,
            },
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
