# Generated by Django 5.2.12 on 2026-06-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_album_cover_image_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumarchive',
            name='pending_hash',
            field=models.CharField(blank=True, default='', help_text='Хеш сборки для существующей задачи.', max_length=64),
        ),
    ]
