# Generated by Django 5.2.12 on 2026-06-25 13:43

import common.storages
import django.db.models.deletion
import store.upload_paths
from django.db import migrations, models

from store.migrations.utils import drop_view, create_view


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_albumarchive_pending_hash'),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AlterField(
            model_name='albumarchive',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает сборки'), ('building', 'Собирается'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='TrackGeneratedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_file', models.FileField(blank=True, storage=common.storages.get_public_media_storage, upload_to=store.upload_paths.track_preview_upload_to, verbose_name='Файл превью')),
                ('preview_duration', models.PositiveIntegerField(blank=True, help_text='Длительность подготовленного превью в секундах', null=True, verbose_name='Длительность превью')),
                ('preview_status', models.CharField(choices=[('pending', 'Ожидает подготовки'), ('building', 'Подготавливается'), ('ready', 'Готов'), ('failed', 'Ошибка подготовки')], default='pending', max_length=32, verbose_name='Статус подготовки превью')),
                ('preview_error', models.TextField(blank=True, verbose_name='Ошибка подготовки превью')),
                ('preview_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало подготовки превью')),
                ('stream_file', models.FileField(blank=True, storage=common.storages.get_private_media_storage, upload_to=store.upload_paths.track_stream_upload_to, verbose_name='Файл для воспроизведения')),
                ('stream_status', models.CharField(choices=[('pending', 'Ожидает подготовки'), ('building', 'Подготавливается'), ('ready', 'Готов'), ('failed', 'Ошибка подготовки')], default='pending', max_length=32, verbose_name='Статус подготовки файла для воспроизведения')),
                ('stream_error', models.TextField(blank=True, verbose_name='Ошибка подготовки файла для воспроизведения')),
                ('stream_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало подготовки файла для воспроизведения')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated', to='store.track', verbose_name='Трек')),
            ],
            options={
                'verbose_name': 'сгенерированные аудиофайлы трека',
                'verbose_name_plural': 'сгенерированные аудиофайлы треков',
            },
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
