# Generated by Django 5.2.12 on 2026-06-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_albumarchive_pending_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['id'], 'verbose_name': 'позиция в корзине', 'verbose_name_plural': 'позиции в корзине'},
        ),
    ]
