# Generated by Django 5.2.12 on 2026-06-24 15:26

import common.storages
import store.upload_paths
from django.db import migrations, models

from store.migrations.utils import create_view, drop_view


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_albumarchive_pending_hash'),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AddField(
            model_name='track',
            name='preview_error',
            field=models.TextField(blank=True, verbose_name='Ошибка подготовки превью'),
        ),
        migrations.AddField(
            model_name='track',
            name='preview_file',
            field=models.FileField(blank=True, storage=common.storages.get_public_media_storage, upload_to=store.upload_paths.track_preview_upload_to, verbose_name='Файл превью'),
        ),
        migrations.AddField(
            model_name='track',
            name='preview_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало подготовки превью'),
        ),
        migrations.AddField(
            model_name='track',
            name='preview_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('ready', 'Готово'), ('failed', 'Ошибка обработки')], default='pending', max_length=32, verbose_name='Статус подготовки превью'),
        ),
        migrations.AddField(
            model_name='track',
            name='stream_error',
            field=models.TextField(blank=True, verbose_name='Ошибка подготовки файла для воспроизведения'),
        ),
        migrations.AddField(
            model_name='track',
            name='stream_file',
            field=models.FileField(blank=True, storage=common.storages.get_private_media_storage, upload_to=store.upload_paths.track_stream_upload_to, verbose_name='Файл для воспроизведения'),
        ),
        migrations.AddField(
            model_name='track',
            name='stream_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало подготовки файла для воспроизведения'),
        ),
        migrations.AddField(
            model_name='track',
            name='stream_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('ready', 'Готово'), ('failed', 'Ошибка обработки')], default='pending', max_length=32, verbose_name='Статус подготовки файла для воспроизведения'),
        ),
        migrations.AlterField(
            model_name='albumarchive',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает сборки'), ('building', 'Собирается'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=32),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
