# Generated by Django 5.2.12 on 2026-06-30 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_albumarchive_status_trackgeneratedaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='created', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID платежа в ЮKassa')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачен'), ('canceled', 'Отменён'), ('failed', 'Ошибка')], default='pending', max_length=255, verbose_name='Статус платежа')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время оплаты')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ключ идемпотентности')),
                ('error_code', models.CharField(blank=True, help_text='Код ошибки, полученный от платежного провайдера', max_length=255, null=True, verbose_name='Код ошибки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
