# Generated by Django 5.2.12 on 2026-07-03 13:45

from django.db import migrations, models

from store.migrations.utils import drop_view, create_view


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_order_status_payment'),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.RemoveField(
            model_name='track',
            name='owner',
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Текст трека'),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
