# Generated by Django 5.2.12 on 2026-07-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_track_owner_alter_track_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reserved_until',
            field=models.DateTimeField(blank=True, help_text='Только автоматическое резервирование, ручное - бессрочно', null=True, verbose_name='Зарезервирован до'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('reserved', 'Резерв'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='created', max_length=20, verbose_name='Статус'),
        ),
    ]
