# Generated by Django 5.2.12 on 2026-07-05 11:26

import common.storages
import django.core.validators
import django.db.models.deletion
import store.upload_paths
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_track_owner_alter_track_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Оригинальный аудиофайл трека.', storage=common.storages.get_private_media_storage, upload_to=store.upload_paths.track_audio_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp3', 'wav', 'flac')), store.validators.FileSizeValidator(max_size_mb=500, optional=False)], verbose_name='Файл трека'),
        ),
        migrations.CreateModel(
            name='TrackUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('initiated', 'Ожидает загрузки'), ('uploaded', 'Файл загружен'), ('completed', 'Загрузка завершена'), ('failed', 'Ошибка загрузки'), ('expired', 'Срок загрузки истёк')], default='initiated', max_length=32, verbose_name='Статус загрузки')),
                ('staging_key', models.CharField(max_length=500, unique=True, verbose_name='Ключ временного файла')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('expected_size', models.PositiveBigIntegerField(verbose_name='Ожидаемый размер файла')),
                ('content_type', models.CharField(blank=True, max_length=255, verbose_name='Заявленный MIME-тип')),
                ('uploaded_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Фактический размер файла')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка загрузки')),
                ('expires_at', models.DateTimeField(verbose_name='Срок действия загрузки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_attempts', to='store.track', verbose_name='Трек')),
            ],
            options={
                'verbose_name': 'загрузка трека',
                'verbose_name_plural': 'загрузки треков',
                'ordering': ('-created_at',),
            },
        ),
    ]
