# Generated by Django 5.2.12 on 2026-07-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_order_reserved_until_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackupload',
            name='purpose',
            field=models.CharField(choices=[('create', 'Создание трека'), ('replace', 'Замена файла')], default='create', max_length=32, verbose_name='Назначение загрузки'),
        ),
    ]
