# Generated by Django 5.2.12 on 2026-07-10 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_order_reserved_until_alter_order_status'),
        ('users', '0020_artistprofile_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cdek_delivery_mode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Метод доставки СДЭК'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код ПВЗ / Постамата'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('courier', 'СДЭК - курьером до двери'), ('pickpoint', 'СДЭК - в пункт выдачи'), ('artist_pickup', 'Самовывоз от артиста')], max_length=20, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cdek_uuid', models.CharField(blank=True, help_text='Уникальный идентификатор запроса в API СДЭК для отслеживания статуса регистрации.', max_length=100, null=True, verbose_name='UUID транзакции СДЭК')),
                ('state', models.CharField(blank=True, help_text='Текущее состояние запроса', max_length=50, null=True, verbose_name='Состояние')),
                ('tracking_number', models.CharField(blank=True, help_text='Номер накладной СДЭК (cdek_number)', max_length=100, null=True, verbose_name='Номер накладной')),
                ('weight', models.PositiveIntegerField(help_text='Общий физический вес посылки.', verbose_name='Вес (в граммах)')),
                ('artist', models.ForeignKey(help_text='Артист, со склада которого уходит посылка.', on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='users.artistprofile', verbose_name='Артист')),
                ('order', models.ForeignKey(help_text='Заказ, к которому относится данное отправление.', on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='store.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'отправление',
                'verbose_name_plural': 'отправления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='store.shipment', verbose_name='Посылка (Отправление)'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('order', 'artist'), name='unique_order_artist_shipment'),
        ),
    ]
