# Generated by Django 5.2.12 on 2026-07-11 16:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_order_cdek_delivery_mode_order_delivery_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cdek_city_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Код населенного пункта в СДЭК'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_calculation',
            field=models.JSONField(blank=True, default=dict, help_text='Расчетная стоимость доставки, полученная от СДЭК на этапе checkout. Формат: {"artist_id": {"cost": "250.00"}}. Используется для фиксации стоимости доставки, которую оплатил клиент.', verbose_name='Стоимость доставки по артистам (руб.)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_delivery_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Предварительная стоимость доставки, рассчитанная через API СДЭК. Может отличаться от фактической стоимости услуг.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Рассчетная стоимость доставки артиста (руб.)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Стоимость доставки всего заказа (руб.)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cdek_uuid',
            field=models.CharField(blank=True, help_text='Уникальный идентификатор запроса в API СДЭК для отслеживания статуса регистрации.', max_length=255, null=True, verbose_name='UUID транзакции СДЭК'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='state',
            field=models.CharField(blank=True, help_text='Текущее состояние запроса', max_length=255, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Номер накладной СДЭК (cdek_number)', max_length=255, null=True, verbose_name='Номер накладной'),
        ),
    ]
