# Generated by Django 5.2.12 on 2026-07-13 08:56

import django.db.models.deletion
from django.db import migrations, models

from store.migrations.utils import drop_view, create_view


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_remove_order_delivery_order_cdek_city_code_and_more'),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.delivery', verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_calculation',
            field=models.JSONField(blank=True, default=dict, help_text='Расчетная стоимость доставки, полученная от СДЭК на этапе checkout. Формат: {"artist_id": {"cost": "0.00"}}.', verbose_name='Стоимость доставки по артистам (руб.)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Общий физический вес посылки.', null=True, verbose_name='Вес (в граммах)'),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
