# Generated by Django 5.2.12 on 2026-07-13 19:40

from django.db import migrations, models

from store.migrations.utils import drop_view, create_view


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_order_delivery_alter_order_delivery_calculation_and_more'),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.JSONField(blank=True, default=dict, help_text='Адрес и дата, где фанат может получить мерч от артиста. Формат: {"address": "Адрес", "date": "YYYY-MM-DD"}.', verbose_name='Адрес самовывоза от артиста'),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
