# Generated by Django 5.2.12 on 2026-07-14 19:32

from django.db import migrations, models

from store.migrations.utils import drop_view, create_view


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_order_delivery_alter_order_delivery_calculation_and_more'),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.JSONField(blank=True, default=dict, help_text='Адрес и дата, где фанат может получить мерч от артиста. Формат: {"address": "Адрес", "date": "YYYY-MM-DD"}.', verbose_name='Адрес самовывоза от артиста'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cdek_city_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Код населенного пункта в СДЭК'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_calculation',
            field=models.JSONField(blank=True, default=dict, help_text='Расчетная стоимость доставки, полученная от СДЭК на этапе checkout. Формат: {"artist_id": {"cost": "0.00"}}.', verbose_name='Стоимость доставки по артистам (руб.)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_point',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Код ПВЗ / Постамата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariffs',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Метод доставки СДЭК'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Общий физический вес посылки.', null=True, verbose_name='Вес (в граммах)'),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
