# Generated by Django 5.2.12 on 2026-07-17 11:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_order_pickup_point_alter_order_cdek_city_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='cdek_uuid',
            field=models.CharField(blank=True, default='', help_text='Уникальный идентификатор запроса в API СДЭК для отслеживания статуса регистрации.', max_length=255, verbose_name='UUID транзакции СДЭК'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='estimated_delivery_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Предварительная стоимость доставки, рассчитанная через API СДЭК. Может отличаться от фактической стоимости услуг.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Расчетная стоимость доставки артиста (руб.)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='state',
            field=models.CharField(blank=True, choices=[('PENDING', 'Отправлено'), ('ACCEPTED', 'Принято'), ('WAITING', 'Ожидание'), ('SUCCESSFUL', 'Успешно'), ('INVALID', 'Ошибка')], default='', help_text='Текущее состояние запроса', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, default='', help_text='Номер накладной СДЭК (cdek_number)', max_length=255, verbose_name='Номер накладной'),
        ),
    ]
