# Generated by Django 5.2.12 on 2026-07-16 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from store.migrations.utils import drop_view, create_view


def fill_content_fields(apps, schema_editor):
    """Заполняет артиста и создателя из существующих связей."""

    Album = apps.get_model('store', 'Album')
    Merch = apps.get_model('store', 'Merch')
    Track = apps.get_model('store', 'Track')
    ArtistProfile = apps.get_model('users', 'ArtistProfile')

    artist_ids_by_user_id = dict(
        ArtistProfile.objects.values_list('user_id', 'id')
    )

    albums_to_update = []
    album_owner_ids = {}

    for album in Album.objects.only(
        'id',
        'owner_id',
        'artist_id',
        'created_by_id',
    ).iterator():
        artist_id = artist_ids_by_user_id.get(album.owner_id)

        if artist_id is None:
            raise RuntimeError(
                'Не найден профиль артиста для альбома '
                f'id={album.id}, owner_id={album.owner_id}.'
            )

        album.artist_id = artist_id
        album.created_by_id = album.owner_id

        albums_to_update.append(album)
        album_owner_ids[album.id] = album.owner_id

    if albums_to_update:
        Album.objects.bulk_update(
            albums_to_update,
            fields=('artist', 'created_by'),
        )

    merch_to_update = []

    for merch in Merch.objects.only(
        'id',
        'owner_id',
        'artist_id',
        'created_by_id',
    ).iterator():
        artist_id = artist_ids_by_user_id.get(merch.owner_id)

        if artist_id is None:
            raise RuntimeError(
                'Не найден профиль артиста для мерча '
                f'id={merch.id}, owner_id={merch.owner_id}.'
            )

        merch.artist_id = artist_id
        merch.created_by_id = merch.owner_id
        merch_to_update.append(merch)

    if merch_to_update:
        Merch.objects.bulk_update(
            merch_to_update,
            fields=('artist', 'created_by'),
        )

    tracks_to_update = []

    for track in Track.objects.only(
        'id',
        'album_id',
        'created_by_id',
    ).iterator():
        created_by_id = album_owner_ids.get(track.album_id)

        if created_by_id is None:
            raise RuntimeError(
                'Не найден владелец альбома для трека '
                f'id={track.id}, album_id={track.album_id}.'
            )

        track.created_by_id = created_by_id
        tracks_to_update.append(track)

    if tracks_to_update:
        Track.objects.bulk_update(
            tracks_to_update,
            fields=('created_by',),
        )


def clear_content_fields(apps, schema_editor):
    """Очищает перенесённые значения при откате миграции."""

    Album = apps.get_model('store', 'Album')
    Merch = apps.get_model('store', 'Merch')
    Track = apps.get_model('store', 'Track')

    Album.objects.update(
        artist=None,
        created_by=None,
    )
    Merch.objects.update(
        artist=None,
        created_by=None,
    )
    Track.objects.update(
        created_by=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_order_pickup_point_alter_order_cdek_city_code_and_more'),
        ('users', '0020_artistprofile_telegram_chat_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='users.artistprofile', verbose_name='Артист'),
        ),
        migrations.AddField(
            model_name='album',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='merch',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='users.artistprofile', verbose_name='Артист'),
        ),
        migrations.AddField(
            model_name='merch',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='track',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.RunPython(
            fill_content_fields,
            clear_content_fields,
        ),
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Получатель выплат'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Получатель выплат'),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
