# Generated by Django 5.2.12 on 2026-07-16 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from store.migrations.utils import create_view, drop_view


def fill_content_relations(apps, schema_editor):
    """Заполняет артиста и создателя из прежнего получателя выплат."""

    Album = apps.get_model('store', 'Album')
    Merch = apps.get_model('store', 'Merch')
    ArtistProfile = apps.get_model('users', 'ArtistProfile')

    artist_ids_by_user_id = dict(
        ArtistProfile.objects
        .exclude(user_id=None)
        .values_list('user_id', 'id')
    )

    for album in Album.objects.all().iterator():
        artist_id = artist_ids_by_user_id.get(
            album.payout_recipient_id,
        )

        if artist_id is None:
            raise RuntimeError(
                'Не найден профиль артиста для альбома '
                f'id={album.pk}, '
                f'payout_recipient_id={album.payout_recipient_id}.'
            )

        album.artist_id = artist_id

        if album.created_by_id is None:
            album.created_by_id = album.payout_recipient_id

        album.save(
            update_fields=(
                'artist',
                'created_by',
            ),
        )

    for merch in Merch.objects.all().iterator():
        artist_id = artist_ids_by_user_id.get(
            merch.payout_recipient_id,
        )

        if artist_id is None:
            raise RuntimeError(
                'Не найден профиль артиста для мерча '
                f'id={merch.pk}, '
                f'payout_recipient_id={merch.payout_recipient_id}.'
            )

        merch.artist_id = artist_id

        if merch.created_by_id is None:
            merch.created_by_id = merch.payout_recipient_id

        merch.save(
            update_fields=(
                'artist',
                'created_by',
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            'store',
            '0041_album_artist_album_created_by_merch_artist_and_more',
        ),
        (
            'users',
            '0021_artistprofile_label_artistprofile_profile_type_and_more',
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.RenameField(
            model_name='album',
            old_name='owner',
            new_name='payout_recipient',
        ),
        migrations.RenameField(
            model_name='merch',
            old_name='owner',
            new_name='payout_recipient',
        ),
        migrations.AlterField(
            model_name='album',
            name='payout_recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payout%(class)s_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Получатель выплат',
            ),
        ),
        migrations.AlterField(
            model_name='merch',
            name='payout_recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payout%(class)s_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Получатель выплат',
            ),
        ),
        migrations.RunPython(
            fill_content_relations,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_items',
                to='users.artistprofile',
                verbose_name='Артист',
            ),
        ),
        migrations.AlterField(
            model_name='merch',
            name='artist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_items',
                to='users.artistprofile',
                verbose_name='Артист',
            ),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
