# Generated by Django 5.2.12 on 2026-07-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from store.migrations.utils import create_view, drop_view


def fill_content_fields(apps, schema_editor):
    """Заполняет артиста и создателя из получателя выплат."""

    Album = apps.get_model('store', 'Album')
    Merch = apps.get_model('store', 'Merch')
    Track = apps.get_model('store', 'Track')
    ArtistProfile = apps.get_model('users', 'ArtistProfile')

    artist_ids_by_user_id = dict(
        ArtistProfile.objects
        .exclude(user_id=None)
        .values_list('user_id', 'id')
    )

    albums_to_update = []
    album_recipient_ids = {}

    for album in Album.objects.only(
        'id',
        'artist_id',
        'created_by_id',
        'payout_recipient_id',
    ).iterator():
        artist_id = artist_ids_by_user_id.get(
            album.payout_recipient_id,
        )

        if artist_id is None:
            raise RuntimeError(
                'Не найден профиль артиста для альбома '
                f'id={album.id}, '
                f'payout_recipient_id={album.payout_recipient_id}.'
            )

        album.artist_id = artist_id
        album.created_by_id = album.payout_recipient_id

        albums_to_update.append(album)
        album_recipient_ids[album.id] = album.payout_recipient_id

    if albums_to_update:
        Album.objects.bulk_update(
            albums_to_update,
            fields=(
                'artist',
                'created_by',
            ),
        )

    merch_to_update = []

    for merch in Merch.objects.only(
        'id',
        'artist_id',
        'created_by_id',
        'payout_recipient_id',
    ).iterator():
        artist_id = artist_ids_by_user_id.get(
            merch.payout_recipient_id,
        )

        if artist_id is None:
            raise RuntimeError(
                'Не найден профиль артиста для мерча '
                f'id={merch.id}, '
                f'payout_recipient_id={merch.payout_recipient_id}.'
            )

        merch.artist_id = artist_id
        merch.created_by_id = merch.payout_recipient_id
        merch_to_update.append(merch)

    if merch_to_update:
        Merch.objects.bulk_update(
            merch_to_update,
            fields=(
                'artist',
                'created_by',
            ),
        )

    tracks_to_update = []

    for track in Track.objects.only(
        'id',
        'album_id',
        'created_by_id',
    ).iterator():
        created_by_id = album_recipient_ids.get(track.album_id)

        if created_by_id is None:
            raise RuntimeError(
                'Не найден получатель выплат альбома для трека '
                f'id={track.id}, album_id={track.album_id}.'
            )

        track.created_by_id = created_by_id
        tracks_to_update.append(track)

    if tracks_to_update:
        Track.objects.bulk_update(
            tracks_to_update,
            fields=('created_by',),
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            'store',
            '0041_alter_shipment_cdek_uuid_and_more',
        ),
        (
            'users',
            '0021_artistprofile_label_artistprofile_profile_type_and_more',
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),

        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_items',
                to='users.artistprofile',
                verbose_name='Артист',
            ),
        ),
        migrations.AddField(
            model_name='album',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='created_%(class)s_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Создал',
            ),
        ),
        migrations.AddField(
            model_name='merch',
            name='artist',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_items',
                to='users.artistprofile',
                verbose_name='Артист',
            ),
        ),
        migrations.AddField(
            model_name='merch',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='created_%(class)s_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Создал',
            ),
        ),
        migrations.AddField(
            model_name='track',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='created_%(class)s_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Создал',
            ),
        ),

        migrations.RenameField(
            model_name='album',
            old_name='owner',
            new_name='payout_recipient',
        ),
        migrations.RenameField(
            model_name='merch',
            old_name='owner',
            new_name='payout_recipient',
        ),

        migrations.AlterField(
            model_name='album',
            name='payout_recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payout%(class)s_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Получатель выплат',
            ),
        ),
        migrations.AlterField(
            model_name='merch',
            name='payout_recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payout%(class)s_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Получатель выплат',
            ),
        ),

        migrations.RunPython(
            fill_content_fields,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_items',
                to='users.artistprofile',
                verbose_name='Артист',
            ),
        ),
        migrations.AlterField(
            model_name='merch',
            name='artist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_items',
                to='users.artistprofile',
                verbose_name='Артист',
            ),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(
                blank=True,
                default='',
                verbose_name='Описание',
            ),
        ),

        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
