# Generated by Django 5.2.12 on 2026-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_shipment_cdek_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='state',
            field=models.CharField(blank=True, choices=[('CREATED', 'Создано'), ('ACCEPTED', 'Принято'), ('WAITING', 'Ожидание'), ('SUCCESSFUL', 'Успешно'), ('INVALID', 'Ошибка')], default='', help_text='Текущее состояние запроса', max_length=20, verbose_name='Состояние'),
        ),
    ]
