# Generated by Django 5.2.12 on 2026-07-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_album_artist_album_created_by_merch_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='tracking_number',
            new_name='cdek_number',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='state',
            field=models.CharField(blank=True, choices=[('CREATED', 'Создано'), ('ACCEPTED', 'Принято'), ('WAITING', 'Ожидание'), ('SUCCESSFUL', 'Успешно'), ('INVALID', 'Ошибка')], default='', help_text='Текущее состояние запроса', max_length=20, verbose_name='Состояние'),
        ),
    ]
