# Generated by Django 5.2.12 on 2026-07-19 09:09

from django.db import migrations, models

from store.migrations.utils import drop_view, create_view


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_rename_tracking_number_shipment_cdek_number_and_more'),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AlterField(
            model_name='product',
            name='property_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название свойства'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='property_value',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Значение свойства'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='state',
            field=models.CharField(blank=True, choices=[('CREATED', 'Создан'), ('ACCEPTED', 'Запрос принят'), ('WAITING', 'Ожидает обработки'), ('SUCCESSFUL', 'Обработан'), ('INVALID', 'Ошибка')], default='', help_text='Текущее состояние запроса', max_length=20, verbose_name='Состояние'),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
