# Generated by Django 5.2.12 on 2026-07-21 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_rename_tracking_number_shipment_cdek_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(help_text='Код промокода может содержать только заглавные латинские буквы, цифры, дефис и подчеркивание.', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(8, message='Код промокода должен содержать минимум 8 символов.'), django.core.validators.RegexValidator(code='invalid_promocode_format', message='Код промокода может содержать только заглавные латинские буквы, цифры, дефис и подчеркивание.', regex='^[A-Z0-9_-]+$')], verbose_name='Код промокода'),
        ),
    ]
