# Generated by Django 5.2.12 on 2026-07-27 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from store.migrations.utils import create_view, drop_view


def migrate_promocode_ownership(apps, schema_editor):
    """Переносит владельца промокода в артиста и создателя."""
    Promocode = apps.get_model('store', 'Promocode')
    ArtistProfile = apps.get_model('users', 'ArtistProfile')

    artist_ids_by_user_id = dict(
        ArtistProfile.objects.filter(
            user_id__isnull=False,
        ).values_list(
            'user_id',
            'id',
        )
    )

    promocodes = list(Promocode.objects.all())

    for promocode in promocodes:
        promocode.artist_id = artist_ids_by_user_id.get(promocode.owner_id)
        promocode.created_by_id = promocode.owner_id

    Promocode.objects.bulk_update(
        promocodes,
        ('artist', 'created_by'),
    )

    promocodes_without_artist = Promocode.objects.filter(
        artist_id__isnull=True,
    )

    if promocodes_without_artist.exists():
        owner_ids = list(
            promocodes_without_artist.values_list(
                'owner_id',
                flat=True,
            )
        )
        raise RuntimeError(
            'Не удалось определить артиста для промокодов владельцев: '
            f'{owner_ids}.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_promocode_code'),
        ('users', '0022_alter_artistprofile_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AddField(
            model_name='promocode',
            name='artist',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='promocodes',
                to='users.artistprofile',
                verbose_name='Артист',
            ),
        ),
        migrations.AddField(
            model_name='promocode',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='created_promocodes',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Создал',
            ),
        ),
        migrations.RunPython(
            migrate_promocode_ownership,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='artist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='promocodes',
                to='users.artistprofile',
                verbose_name='Артист',
            ),
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='owner',
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
