# Generated by Django 5.2.12 on 2026-07-23 19:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models

from store.migrations.utils import drop_view, create_view


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_promocode_code'),
        ('users', '0021_artistprofile_label_artistprofile_profile_type_and_more'),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AddField(
            model_name='orderitem',
            name='platform_commission',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Комиссия платформы (руб.)'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('period_type', models.CharField(choices=[('day', 'День'), ('month', 'Месяц')], max_length=10, verbose_name='Тип периода')),
                ('status', models.CharField(choices=[('pending', 'Формируется'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус отчета')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Количество заказов')),
                ('items_count', models.PositiveIntegerField(default=0, verbose_name='Количество проданных товаров')),
                ('gross_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Валовая выручка, руб.')),
                ('discount_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Сумма скидок, руб.')),
                ('delivery_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Стоимость доставки, руб.')),
                ('commission_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Комиссия платформы, руб.')),
                ('payout_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Сумма к выплате, руб.')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Файл отчета')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='users.artistprofile', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'отчет',
                'verbose_name_plural': 'отчеты',
                'ordering': ('-period_end', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('artist', 'period_type', 'period_start', 'period_end'), name='unique_artist_report')],
            },
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
