# Generated by Django 5.2.12 on 2026-08-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_orderitem_platform_commission_and_more'),
        ('users', '0023_artistpickuppoint_unique_active_artist_pickup_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-created_at',), 'verbose_name': 'отчет', 'verbose_name_plural': 'отчеты'},
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_artist_report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='report',
            name='donation_amount',
        ),
        migrations.RemoveField(
            model_name='report',
            name='items_count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='orders_count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='period_type',
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('artist', 'period_start', 'period_end'), name='unique_artist_report'),
        ),
    ]
