# Generated by Django 5.2.12 on 2026-08-07 20:01

from decimal import Decimal
from django.db import migrations, models

from store.migrations.utils import create_view, drop_view
class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_orderitem_platform_commission_and_more'),
        ('users', '0025_artiststoresettings'),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-created_at',), 'verbose_name': 'отчет', 'verbose_name_plural': 'отчеты'},
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_artist_report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='delivery_amount',
        ),
        migrations.RemoveField(
            model_name='report',
            name='items_count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='orders_count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='period_type',
        ),
        migrations.AlterField(
            model_name='report',
            name='donation_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Сумма доплат, руб.'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('artist', 'period_start', 'period_end'), name='unique_artist_report'),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
