# Generated by Django 5.2.12 on 2026-08-22 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q

from store.migrations.utils import create_view, drop_view


def fill_order_item_snapshots(apps, schema_editor):
    """Заполняет артиста и получателя выплаты для существующих позиций заказа."""
    OrderItem = apps.get_model('store', 'OrderItem')
    Merch = apps.get_model('store', 'Merch')

    merch_has_artist = any(
        field.name == 'artist'
        for field in Merch._meta.get_fields()
    )

    select_related = [
        'product_variant__product__album',
        'product_variant__product__track__album',
        'product_variant__product__merch',
    ]

    if merch_has_artist:
        select_related.append('product_variant__product__merch__artist')
    else:
        select_related.append(
            'product_variant__product__merch__owner__artist_profile'
        )

    queryset = (
        OrderItem.objects
        .filter(
            Q(artist__isnull=True)
            | Q(payout_recipient__isnull=True)
        )
        .select_related(*select_related)
    )

    items_to_update = []

    for item in queryset.iterator(chunk_size=500):
        product = item.product_variant.product

        artist_id = None
        payout_recipient_id = None

        if product.album_id:
            artist_id = product.album.artist_id
            payout_recipient_id = product.album.payout_recipient_id

        elif product.track_id:
            album = product.track.album
            artist_id = album.artist_id
            payout_recipient_id = album.payout_recipient_id

        elif product.merch_id:
            merch = product.merch

            if merch_has_artist:
                artist_id = merch.artist_id
            else:
                artist_id = merch.owner.artist_profile.id

            payout_recipient_id = merch.payout_recipient_id

        if artist_id is None or payout_recipient_id is None:
            raise RuntimeError(
                'Не удалось определить snapshot для '
                f'OrderItem id={item.pk}'
            )

        item.artist_id = artist_id
        item.payout_recipient_id = payout_recipient_id
        items_to_update.append(item)

        if len(items_to_update) >= 500:
            OrderItem.objects.bulk_update(
                items_to_update,
                ['artist', 'payout_recipient'],
                batch_size=500,
            )
            items_to_update.clear()

    if items_to_update:
        OrderItem.objects.bulk_update(
            items_to_update,
            ['artist', 'payout_recipient'],
            batch_size=500,
        )

    unresolved_items = OrderItem.objects.filter(
        Q(artist__isnull=True)
        | Q(payout_recipient__isnull=True)
    )

    if unresolved_items.exists():
        raise RuntimeError(
            'После миграции остались OrderItem без артиста '
            'или получателя выплаты'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_alter_report_options_and_more'),
        ('users', '0027_emailverificationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AddField(
            model_name='orderitem',
            name='artist',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='order_items',
                to='users.artistprofile',
                verbose_name='Артист на момент покупки',
            ),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payout_recipient',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payout_order_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Получатель выплаты на момент покупки',
            ),
        ),
        migrations.RunPython(
            fill_order_item_snapshots,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='artist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='order_items',
                to='users.artistprofile',
                verbose_name='Артист на момент покупки',
            ),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payout_recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payout_order_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Получатель выплаты на момент покупки',
            ),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
