# Generated by Django 5.2.12 on 2026-08-24 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_report_payout_recipients(apps, schema_editor):
    Report = apps.get_model('store', 'Report')

    reports = Report.objects.select_related('artist').iterator()

    for report in reports:
        if report.artist.user_id is None:
            raise RuntimeError(
                f'Не удалось определить получателя выплаты '
                f'для отчета {report.pk}: '
                f'у артиста {report.artist_id} нет пользователя.'
            )

        report.payout_recipient_id = report.artist.user_id
        report.save(update_fields=['payout_recipient'])


def restore_report_artists(apps, schema_editor):
    Report = apps.get_model('store', 'Report')
    ArtistProfile = apps.get_model('users', 'ArtistProfile')

    reports = Report.objects.select_related('payout_recipient').iterator()

    for report in reports:
        artist = ArtistProfile.objects.filter(
            user_id=report.payout_recipient_id,
        ).first()

        if artist is None:
            raise RuntimeError(
                f'Не удалось восстановить артиста '
                f'для отчета {report.pk}: '
                f'у получателя {report.payout_recipient_id} '
                f'нет профиля артиста.'
            )

        report.artist_id = artist.id
        report.save(update_fields=['artist'])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_orderitem_artist_orderitem_payout_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='payout_recipient',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reports',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Получатель выплаты',
            ),
        ),
        migrations.RunPython(
            fill_report_payout_recipients,
            restore_report_artists,
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_artist_report',
        ),
        migrations.AlterField(
            model_name='report',
            name='payout_recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reports',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Получатель выплаты',
            ),
        ),
        migrations.RemoveField(
            model_name='report',
            name='artist',
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(
                fields=(
                    'payout_recipient',
                    'period_start',
                    'period_end',
                ),
                name='unique_payout_recipient_report',
            ),
        ),
    ]
