# Generated by Django 5.2.12 on 2026-08-24 14:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_report_payout_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Сумма выплаты, руб.')),
                ('status', models.CharField(choices=[('pending', 'Ожидает выплаты'), ('on_hold', 'Отложена'), ('paid', 'Выплачено')], default='pending', max_length=10, verbose_name='Статус выплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('payout_recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL, verbose_name='Получатель выплаты')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='store.report', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'выплата',
                'verbose_name_plural': 'выплаты',
                'ordering': ('-created_at',),
            },
        ),
    ]
