# Generated by Django 5.2.12 on 2026-08-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceOperations',
            fields=[
            ],
            options={
                'verbose_name': 'сервисная операция',
                'verbose_name_plural': 'сервисные операции',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.album',),
        ),
    ]
