# Generated by Django 5.2.12 on 2026-08-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_maintenanceoperations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merch',
            options={'ordering': ('name',), 'verbose_name': 'мерч', 'verbose_name_plural': 'мерч'},
        ),
        migrations.AlterModelOptions(
            name='merchkind',
            options={'ordering': ('-is_carrier', 'name'), 'verbose_name': 'тип мерча', 'verbose_name_plural': 'типы мерча'},
        ),
    ]
