# Generated by Django 5.2.12 on 2026-08-28 07:17

from django.db import migrations

from store.migrations.utils import create_materialized_view


CREATE_EXTENSION_SQL = """
CREATE EXTENSION IF NOT EXISTS pg_trgm;
"""


CREATE_INDEXES_SQL = """
CREATE UNIQUE INDEX catalog_search_id_idx
ON catalog_search (id);

CREATE UNIQUE INDEX catalog_search_entity_idx
ON catalog_search (entity_type, entity_id);

CREATE INDEX catalog_search_search_vector_idx
ON catalog_search
USING GIN (search_vector);

CREATE INDEX catalog_search_search_text_trgm_idx
ON catalog_search
USING GIN (search_text gin_trgm_ops);
"""


DROP_INDEXES_SQL = """
DROP INDEX IF EXISTS catalog_search_search_text_trgm_idx;
DROP INDEX IF EXISTS catalog_search_search_vector_idx;
DROP INDEX IF EXISTS catalog_search_entity_idx;
DROP INDEX IF EXISTS catalog_search_id_idx;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_alter_merch_options_alter_merchkind_options'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_EXTENSION_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        create_materialized_view(
            'catalog_search',
            version=1,
        ),
        migrations.RunSQL(
            sql=CREATE_INDEXES_SQL,
            reverse_sql=DROP_INDEXES_SQL,
        ),
    ]
