# Generated by Django 5.2.12 on 2026-08-28 07:17

from django.db import migrations

from store.migrations.utils import (
    create_materialized_view,
    create_materialized_view_indexes,
    create_postgres_extension,
)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_alter_merch_options_alter_merchkind_options'),
    ]

    operations = [
        create_postgres_extension('pg_trgm'),
        create_materialized_view('catalog_search', version=1),
        create_materialized_view_indexes('catalog_search', version=1),
    ]
