# Generated by Django 5.2.12 on 2026-08-28 07:17

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_create_catalog_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSearch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID строки индекса')),
                ('entity_type', models.CharField(max_length=20, verbose_name='Тип сущности')),
                ('entity_id', models.PositiveBigIntegerField(verbose_name='ID сущности')),
                ('target_id', models.PositiveBigIntegerField(null=True, verbose_name='ID целевой сущности')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('artist_name', models.CharField(max_length=255, null=True, verbose_name='Артист')),
                ('genre_name', models.CharField(max_length=255, null=True, verbose_name='Жанр')),
                ('merch_kind_name', models.CharField(max_length=255, null=True, verbose_name='Тип мерча')),
                ('variant_values', models.TextField(null=True, verbose_name='Значения вариантов')),
                ('selected_variant_id', models.PositiveBigIntegerField(null=True, verbose_name='Выбранный вариант')),
                ('is_publication_ready', models.BooleanField(null=True, verbose_name='Готовность к публикации')),
                ('search_text', models.TextField(verbose_name='Поисковый текст')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(verbose_name='Поисковый вектор')),
                ('image', models.CharField(max_length=255, null=True, verbose_name='Изображение')),
            ],
            options={
                'db_table': 'catalog_search',
                'managed': False,
            },
        ),
    ]
