# Generated by Django 5.2.12 on 2026-09-06 04:44

from django.db import migrations, models

from store.migrations.utils import create_view, drop_view


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_catalogsearch'),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AddField(
            model_name='order',
            name='delivery_point_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес ПВЗ / Постамата'),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
