# Generated by Django 5.2.12 on 2026-09-16 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from store.migrations.utils import drop_view, create_view


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_order_delivery_point_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AlterField(
            model_name='album',
            name='payout_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Получатель выплат'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='payout_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Получатель выплат'),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
