# Generated by Django 5.2.12 on 2026-09-16 12:21

from django.conf import settings
from django.db import migrations, models

from store.migrations.utils import drop_view, create_view


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_alter_album_payout_recipient_and_more'),
        ('users', '0034_remove_artistprofile_artist_profile_has_user_or_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        drop_view('listener_album_access'),
        drop_view('listener_track_access'),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', False), ('payout_recipient__isnull', False), _connector='OR'), name='album_published_requires_payout_recipient'),
        ),
        migrations.AddConstraint(
            model_name='merch',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', False), ('payout_recipient__isnull', False), _connector='OR'), name='merch_published_requires_payout_recipient'),
        ),
        create_view('listener_track_access', version=1),
        create_view('listener_album_access', version=1),
    ]
