# Generated by Django 5.2.12 on 2026-10-07 15:15

import common.storages
import django.core.validators
import django.db.models.deletion
import store.upload_paths
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_album_album_published_requires_payout_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название бонуса')),
                ('bonus_file', models.FileField(storage=common.storages.get_public_media_storage, upload_to=store.upload_paths.bonus_audio_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'jpg', 'png', 'mp4', 'txt', 'zip')), store.validators.FileSizeValidator(max_size_mb=500, optional=False)], verbose_name='Файл бонуса')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='store.album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'бонус',
                'verbose_name_plural': 'бонусы',
                'ordering': ('name',),
            },
        ),
    ]
