# Generated by Django 5.2.12 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_album_album_published_requires_payout_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogMigrationMapping',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('bundle_version', models.CharField(max_length=32)),
                (
                    'entity_type',
                    models.CharField(
                        choices=[
                            ('profile', 'Профиль'),
                            ('release', 'Релиз'),
                            ('track', 'Трек'),
                            ('merch', 'Мерч'),
                            ('product', 'Продукт'),
                            ('variant', 'Вариант'),
                        ],
                        max_length=16,
                    ),
                ),
                ('source_entity_id', models.CharField(max_length=255)),
                ('django_pk', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'соответствие миграции каталога',
                'verbose_name_plural': 'соответствия миграции каталога',
                'constraints': [
                    models.UniqueConstraint(
                        fields=(
                            'bundle_version',
                            'entity_type',
                            'source_entity_id',
                        ),
                        name='unique_catalog_migration_source',
                    ),
                    models.UniqueConstraint(
                        fields=('entity_type', 'django_pk'),
                        name='unique_catalog_migration_target',
                    ),
                ],
            },
        ),
    ]
