# Generated by Django 5.2.12 on 2026-09-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Добавляет устойчивое состояние миграционного аудио."""

    dependencies = [
        ('store', '0058_catalogmigrationmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogMigrationAudioState',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления',
                    ),
                ),
                ('asset_id', models.CharField(max_length=255)),
                ('source_key', models.CharField(max_length=1000)),
                ('source_sha256', models.CharField(max_length=64)),
                ('expected_size', models.PositiveBigIntegerField()),
                ('staging_key', models.CharField(max_length=500, unique=True)),
                (
                    'original_key',
                    models.CharField(max_length=500, unique=True),
                ),
                ('preview_key', models.CharField(blank=True, max_length=500)),
                ('stream_key', models.CharField(blank=True, max_length=500)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('prepared', 'Подготовлено'),
                            ('copying', 'Копируется в staging'),
                            ('staged', 'Оригинал подключён'),
                            ('queued', 'Поставлено в очередь'),
                            ('processing', 'Обрабатывается'),
                            ('ready', 'Готово'),
                            ('failed', 'Ошибка'),
                        ],
                        default='prepared',
                        max_length=16,
                    ),
                ),
                ('error', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                (
                    'mapping',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='audio_state',
                        to='store.catalogmigrationmapping',
                    ),
                ),
                (
                    'track',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='migration_audio_state',
                        to='store.track',
                    ),
                ),
                (
                    'upload',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='migration_audio_state',
                        to='store.trackupload',
                    ),
                ),
            ],
            options={
                'verbose_name': 'состояние аудио миграции каталога',
                'verbose_name_plural': 'состояния аудио миграции каталога',
            },
        ),
    ]
