# Generated by Django 5.2.12 on 2026-10-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_bonus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ('position', 'name'), 'verbose_name': 'бонус', 'verbose_name_plural': 'бонусы'},
        ),
        migrations.AddField(
            model_name='bonus',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='Порядковый номер бонуса в списке', null=True, verbose_name='Порядок'),
        ),
    ]
