volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:17.5
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: inswty/zvuchno_backend:latest
    env_file: .env
    user: "${UID}:${GID}"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - db
  gateway:
    image: inswty/zvuchno_gateway:latest
    env_file: .env
    volumes:
      - ./staticfiles:/staticfiles:ro
      - ./media:/media:ro
    depends_on:
      - backend
    ports:
      - "127.0.0.1:8000:80"
