"""Константы, используемые в приложении store."""

from decimal import Decimal

ALLOWED_AUDIO_EXTENSIONS = ('mp3', 'wav', 'flac')
MAX_CHAR_LENGTH = 255
MAX_IMAGE_SIZE_MB = 10
MAX_AUDIOFILE_SIZE_MB = 500
MAX_PRICE_DIGITS = 10
MAX_SLUG_LENGTH = 50
MAX_STR_LENGTH = 40
MAX_NUMBER_ORDER_LENGTH = 15
MAX_COMMENT_LENGTH = 200
MAX_PROMOCODE_LENGTH = 32
PROMOCODE_FORMAT_HELP_TEXT = (
    'Код промокода может содержать только заглавные '
    'латинские буквы, цифры, дефис и подчеркивание.'
)
ZERO_MONEY = Decimal('0.0000')
MONEY_INTERNAL_PRECISION = 4
MONEY_DISPLAY_PRECISION = 2
DISCOUNT_VALUE_PRECISION = 2
CHAR_PRESET_SIMPLE = 'simple'
CHAR_PRESET_DIGITAL = 'digital'

# Константы для мерча
DESCRIPTION_MERCH_MAX_LENGTH = 1000
VISIBILITY_MAX_LENGTH = 20
DEFAULT_QUANTITY = 0
MAX_IMAGE_FOR_MERCH = 4

CDEK_API_PAGE_SIZE = 1000
DEFAULT_CACHE_TIMEOUT = 60 * 60 * 24
CITY_CACHE_TIMEOUT = 60 * 60 * 24 * 30
CDEK_API_MAX_PAGES = 20

MAX_FILE_STATUS_STR = 32
PREVIEW_DURATION = 30
PREVIEW_CROSSFADE_DURATION = 1
PREVIEW_SEGMENT_DURATION = (PREVIEW_DURATION + PREVIEW_CROSSFADE_DURATION) / 2
STREAM_BITRATE = '256k'
PREVIEW_BITRATE = '256k'
AUDIO_PROCESSING_TIMEOUT = 20 * 60
