"""
Константы, используемые в приложении store.
"""

ALLOWED_AUDIO_EXTENSIONS = ('mp3', 'wav', 'flac')
MAX_CHAR_LENGTH = 256
MAX_IMAGE_SIZE_MB = 10
MAX_PRICE_DIGITS = 10
MAX_SLUG_LENGTH = 50
MAX_STR_LENGTH = 40
PRICE_DECIMAL_PLACES = 2  # Количество цифр после запятой


# Константы для мерча
NAME_MERCH_MAX_LENGTH = 128
DESCRIPTION_MERCH_MAX_LENGTH = 1000
MAX_PRICE_DIGITS = 10
PRICE_DECIMAL_PLACEC = 2  # Количество цифр после запятой
VISIBILITY_MAX_LENGTH = 20
DEFAULT_QUANTITY = 0
MAX_IMAGE_FOR_MERCH = 4
