"""Константы, используемые в приложении store."""

ALLOWED_AUDIO_EXTENSIONS = ('mp3', 'wav', 'flac')
MAX_CHAR_LENGTH = 255
MAX_IMAGE_SIZE_MB = 10
MAX_PRICE_DIGITS = 10
MAX_SLUG_LENGTH = 50
MAX_STR_LENGTH = 40
MAX_COMMENT_LENGTH = 200
MONEY_INTERNAL_PRECISION = 4
MONEY_DISPLAY_PRECISION = 2

# Константы для мерча
DESCRIPTION_MERCH_MAX_LENGTH = 1000
VISIBILITY_MAX_LENGTH = 20
DEFAULT_QUANTITY = 0
MAX_IMAGE_FOR_MERCH = 4
