"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import logging
import os
from datetime import timedelta
from pathlib import Path

import sentry_sdk
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration

from .admin_reorder_config import ADMIN_REORDER  # noqa
from config import logging as logging_config
from config.glitchtip import init_glitchtip

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.vk',
    'allauth.socialaccount.providers.yandex',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'nested_admin',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'dj_rest_auth',
    'djoser',
    'phonenumber_field',
    'admin_reorder',
    'users.apps.UsersConfig',
    'store.apps.StoreConfig',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
    'allauth.account.middleware.AccountMiddleware',
]

# Настройки Silk и nplusone
if DEBUG:
    INSTALLED_APPS += ['silk']
    MIDDLEWARE = ['silk.middleware.SilkyMiddleware'] + MIDDLEWARE
    SILKY_PYTHON_PROFILER = True  # Включает профилирование Python-кода
    SILKY_INTERCEPT_PERCENT = 100 # Записывать 100% запросов (для дебага)
    SILKY_MAX_RECORDED_STACKTRACES = 10 # Ограничение стека, чтобы не раздувать БД
    SILKY_META = True # Записывать время генерации самого Silk

    INSTALLED_APPS += ['nplusone.ext.django']
    MIDDLEWARE = ['nplusone.ext.django.NPlusOneMiddleware'] + MIDDLEWARE
    NPLUSONE_RAISE = False  # Не выбрасывать ошибку
    NPLUSONE_LOGGER = logging.getLogger('nplusone')
    NPLUSONE_LOG_LEVEL = logging.WARN
    NPLUSONE_WHITELIST = [{'model': 'silk.*'}]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
USE_SQLITE = os.getenv('USE_SQLITE', 'True') == 'True'
if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ['POSTGRES_USER'],
            'PASSWORD': os.environ['POSTGRES_PASSWORD'],
            'HOST': os.environ['POSTGRES_HOST'],
            'PORT': os.environ['POSTGRES_PORT'],
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SPECTACULAR_SETTINGS = {
    'TITLE': 'Zvuchno API',
    'DESCRIPTION': 'Документация API проекта',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,  # Разделяет сериализаторы input/output
    'COMPONENT_SPLIT_PATCH': True,  # Для PATCH чтобы все поля - необязательные
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,  # Не вылетает логин при обновлении
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/app/staticfiles'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# S3
MEDIA_LOCATION = os.getenv('MEDIA_LOCATION', 'media')
USE_S3_MEDIA = os.getenv('USE_S3_MEDIA', 'False').lower() == 'true'

def get_required_env(name: str) -> str:
    """Возвращает обязательную переменную окружения."""
    value = os.getenv(name)
    if not value:
        raise ImproperlyConfigured(
            f'Переменная окружения {name} обязательна при USE_S3_MEDIA=True.',
        )
    return value

if USE_S3_MEDIA:
    AWS_ACCESS_KEY_ID = get_required_env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = get_required_env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = get_required_env('AWS_STORAGE_BUCKET_NAME')

    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL', 'https://storage.yandexcloud.net')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'ru-central1')
    AWS_S3_ADDRESSING_STYLE = os.getenv('AWS_S3_ADDRESSING_STYLE', 'path')

    AWS_QUERYSTRING_AUTH = os.getenv('AWS_QUERYSTRING_AUTH', 'False').lower() == 'true'
    AWS_QUERYSTRING_EXPIRE = int(os.getenv('AWS_QUERYSTRING_EXPIRE', 120))
    AWS_S3_FILE_OVERWRITE = os.getenv('AWS_S3_FILE_OVERWRITE', 'False').lower() == 'true'
    AWS_DEFAULT_ACL = None

    # Включаем S3 только для медиа, статика остается локальной
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'location': f'{MEDIA_LOCATION}/private',
                'querystring_auth': True,
                'default_acl': None,
            },
        },
        'public_media': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'location': f'{MEDIA_LOCATION}/public',
                'querystring_auth': False,
                'default_acl': None,
            },
        },
        'private_media': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'location': f'{MEDIA_LOCATION}/private',
                'querystring_auth': True,
                'default_acl': None,
            },
        },
        'staticfiles': {
            'BACKEND': (
                'django.contrib.staticfiles.storage.StaticFilesStorage'
            ),
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'public_media': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'private_media': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': (
                'django.contrib.staticfiles.storage.StaticFilesStorage'
            ),
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DJOSER = {
    'SERIALIZERS': {
    }
}

AUTH_USER_MODEL = 'users.CoreUser'

PHONENUMBER_DEFAULT_REGION = 'RU'

FRONTEND_VERIFY_EMAIL_URL = os.getenv('FRONTEND_VERIFY_EMAIL_URL', 'http://localhost:3000/verify-email')
FRONTEND_RESET_PASSWORD_URL = os.getenv('FRONTEND_RESET_PASSWORD_URL', 'http://localhost:3000/reset-password-confirm')

# Настройки CELERY
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')

if DEBUG:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_SOFT_TIME_LIMIT = 240
CELERY_TASK_TIME_LIMIT = 300

if DEBUG:
    # Локальная разработка: кэш в оперативной памяти
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
else:
    # Продакшн: Redis
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://redis:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }

# Настройки CDEK
CDEK_API_URL = os.getenv('CDEK_API_URL')
CDEK_CLIENT_ID = os.getenv('CDEK_CLIENT_ID')
CDEK_CLIENT_SECRET = os.getenv('CDEK_CLIENT_SECRET')
DEFAULT_CITY = os.getenv('DEFAULT_CITY')
GEO_PROVIDER = os.getenv('GEO_PROVIDER')

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_RATES': {

        'anon': '200/min',
        'user': '600/min',

        'login': '5/min',
        'social_auth': '10/min',
        'registration': '5/min',
        'logout': '10/min',

        'refresh': '10/min',
        'verify': '20/min',

        'change_phone': '5/min',
        'change_username': '5/min',
        'change_password': '5/min',

        'reset_password_verify': '5/min',
        'reset_password_request': '5/min',
        'reset_password_confirm': '5/min',

        'verify_email': '10/min',
        'resend_verification_email': '5/min',

        'become_artist': '5/min',
        'artist_legal_profile': '60/min',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.DefaultLimitOffsetPagination',
}

# TODO: настроить периодический запуск flushexpiredtokens
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.getenv('JWT_ACCESS_MINUTES', 30))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.getenv('JWT_REFRESH_DAYS', 7))
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
REST_AUTH = {
    'USE_JWT': True,
    'TOKEN_MODEL': None,
    'JWT_AUTH_HTTPONLY': False,
    'JWT_SERIALIZER': 'users.serializers.TokenPairSerializer',
}
SITE_ID = 1  # id записи таблицы sites, где указан домен бэкенда для allauth.
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_PROVIDERS = {
    'vk': {
        'SCOPE': ['email'],
        'VERIFIED_EMAIL': True,  # доверяем почте из Вк.
        'AUTH_PARAMS': {'prompt': 'login'},
    },
    'yandex': {
        'SCOPE': ['login:email'],
        'VERIFIED_EMAIL': True,  # доверяем почте из Я.
        'AUTH_PARAMS': {'force_confirm': 'yes'},
    }
}
SOCIALACCOUNT_ADAPTER = 'users.adapters.SocialAccountAdapter'
SOCIALACCOUNT_QUERY_EMAIL = True  # запрашивать email у провайдера
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True  # разрешить вход по email из соцсети
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True  # автоматически связывать
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_LOGIN_ON_GET = True  # сразу редиректить вход без промежуточной страницы
FRONTEND_SOCIAL_AUTH_URL = os.getenv(
    'FRONTEND_SOCIAL_AUTH_URL',
    '/'
)
LOGIN_REDIRECT_URL = FRONTEND_SOCIAL_AUTH_URL  # Для успешных входов по умолчанию
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
# SESSION_COOKIE_AGE = 86400

LOGGING = logging_config.LOGGING

# Настройка отправки ошибок проекта в GlitchTip
init_glitchtip()

#CORS
DEFAULT_CORS_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
EXTRA_CORS_ORIGINS = []
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
    EXTRA_CORS_ORIGINS = [o.strip() for o in origins.split(',') if o.strip()]

CORS_ALLOWED_ORIGINS = list({
    *DEFAULT_CORS_ORIGINS,
    *EXTRA_CORS_ORIGINS,
})

# EMAIL backend
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    EMAIL_FILE_PATH = BASE_DIR / 'tmp' / 'emails'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', 10))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
