# Константы модели пользователя
EMAIL_FIELD_MAX_LENGTH = 254
EMAIL_FIELD_MIN_LENGTH = 5
USERNAME_FIELD_MAX_LENGTH = 150
USERNAME_FIELD_MIN_LENGTH = 1

# Константы профиля
CITY_FIELD_MAX_LENGTH = 254
CITY_FIELD_MIN_LENGTH = 2
ARTIST_NAME_FIELD_MAX_LENGTH = 254
ARTIST_NAME_FIELD_MIN_LENGTH = 2
ARTIST_DESC_FIELD_MAX_LENGTH = 3000
ARTIST_DESC_FIELD_MIN_LENGTH = 10
ARTIST_LINK_LABEL_MAX_LENGTH = 254
ARTIST_LINK_LABEL_MIN_LENGTH = 3
ARTIST_LINK_FIELD_MAX_LENGTH = 254
ARTIST_LINK_FIELD_MIN_LENGTH = 3
ARTIST_LINK_TYPE_MAX_LENGTH = 32
URL_FIELD_MAX_LENGTH = 254
URL_FIELD_MIN_LENGTH = 3
FULL_NAME_FIELD_MAX_LENGTH = 254
MAX_USER_CREATE_ATTEMPTS = 30

# Artist legal data
NAME_FIELD_MAX_LENGTH = 150
ADDRESS_FIELD_MAX_LENGTH = 500

PASSPORT_SERIES_MAX_LENGTH = 10
PASSPORT_NUMBER_MAX_LENGTH = 20
PASSPORT_ISSUED_BY_MAX_LENGTH = 255

RECIPIENT_TYPE_MAX_LENGTH = 50

INN_MAX_LENGTH = 12

BANK_NAME_MAX_LENGTH = 255
BIK_MAX_LENGTH = 9
ACCOUNT_NUMBER_MAX_LENGTH = 20

TAXATION_FORM_MAX_LENGTH = 32
